/* GENERATED by scripts/gen-faust.ts from faust_voice.dsp via Faust */
/* Regenerate with: mise run gen-faust (or: pnpm run gen-faust) */

/* ------------------------------------------------------------
name: "faust_voice"
Code generated with Faust 2.85.5 (https://faust.grame.fr)
Compilation options: -a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn faust_voice_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0
------------------------------------------------------------ */

#ifndef  __faust_voice_faust_H__
#define  __faust_voice_faust_H__

/* Faust architecture file: library-only output.
 *
 * Used by scripts/gen-faust.ts to generate the per-module C from a .dsp
 * source. Produces only the DSP class definitions (struct + functions like
 * `new<prefix>`, `init<prefix>`, `compute<prefix>`, `buildUserInterface<prefix>`)
 * with no `main()`. The moveforge per-module adapter
 * (`<id>_core.c`) consumes that output.
 *
 * Faust replaces <<includeIntrinsic>> and <<includeclass>> at codegen time.
 * Keep this file small and dependency-light so the generated artifact stays
 * portable and drops cleanly into the existing Schwung wrapper pipeline.
 */

#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif

/* The generated `buildUserInterface` walks a UIGlue struct of callbacks.
 * We don't use Faust's UI to discover params at runtime — the moveforge
 * adapter knows param indices statically — so we provide a stub type
 * that satisfies the symbol without pulling in Faust's UI runtime. */
typedef struct UIGlue UIGlue;
typedef struct MetaGlue MetaGlue;


#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 


#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

/* link with : "" */
#include <math.h>
#include <stdint.h>
#include <stdlib.h>

static float faust_voice_faust_faustpower2_f(float value) {
	return value * value;
}

#ifndef FAUSTCLASS 
#define FAUSTCLASS faust_voice_faust
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif
#ifndef FAUSTMAXI
#define FAUSTMAXI
inline int faustmaxi(int a, int b) { return (a > b) ? a : b; }
inline int faustmini(int a, int b) { return (a < b) ? a : b; }
#endif

typedef struct {
	FAUSTFLOAT fHslider0;
	FAUSTFLOAT fHslider1;
	int fSampleRate;
	float fConst0;
	float fConst1;
	FAUSTFLOAT fHslider2;
	FAUSTFLOAT fHslider3;
	float fConst2;
	FAUSTFLOAT fHslider4;
	float fRec1[2];
	FAUSTFLOAT fHslider5;
	FAUSTFLOAT fHslider6;
	float fVec0[2];
	float fRec3[2];
	FAUSTFLOAT fHslider7;
	int iRec4[2];
	float fRec0[3];
} faust_voice_faust;

faust_voice_faust* newfaust_voice_faust() { 
	faust_voice_faust* dsp = (faust_voice_faust*)calloc(1, sizeof(faust_voice_faust));
	return dsp;
}

void deletefaust_voice_faust(faust_voice_faust* dsp) { 
	free(dsp);
}

void metadatafaust_voice_faust(MetaGlue* m) { 
	m->declare(m->metaInterface, "compile_options", "-a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn faust_voice_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 0");
	m->declare(m->metaInterface, "envelopes.lib/adsr:author", "Yann Orlarey and Andrey Bundin");
	m->declare(m->metaInterface, "envelopes.lib/author", "GRAME");
	m->declare(m->metaInterface, "envelopes.lib/copyright", "GRAME");
	m->declare(m->metaInterface, "envelopes.lib/license", "LGPL with exception");
	m->declare(m->metaInterface, "envelopes.lib/name", "Faust Envelope Library");
	m->declare(m->metaInterface, "envelopes.lib/version", "1.3.0");
	m->declare(m->metaInterface, "filename", "faust_voice.dsp");
	m->declare(m->metaInterface, "filters.lib/fir:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/fir:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/iir:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/iir:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/name", "Faust Filters Library");
	m->declare(m->metaInterface, "filters.lib/resonlp:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/resonlp:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/resonlp:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/tf2:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/tf2:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/tf2s:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/tf2s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/tf2s:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/version", "1.7.1");
	m->declare(m->metaInterface, "maths.lib/author", "GRAME");
	m->declare(m->metaInterface, "maths.lib/copyright", "GRAME");
	m->declare(m->metaInterface, "maths.lib/license", "LGPL with exception");
	m->declare(m->metaInterface, "maths.lib/name", "Faust Math Library");
	m->declare(m->metaInterface, "maths.lib/version", "2.9.0");
	m->declare(m->metaInterface, "name", "faust_voice");
	m->declare(m->metaInterface, "oscillators.lib/name", "Faust Oscillator Library");
	m->declare(m->metaInterface, "oscillators.lib/saw2ptr:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "oscillators.lib/saw2ptr:license", "STK-4.3");
	m->declare(m->metaInterface, "oscillators.lib/version", "1.7.0");
	m->declare(m->metaInterface, "platform.lib/name", "Generic Platform Library");
	m->declare(m->metaInterface, "platform.lib/version", "1.3.0");
}

int getSampleRatefaust_voice_faust(faust_voice_faust* RESTRICT dsp) {
	return dsp->fSampleRate;
}

int getNumInputsfaust_voice_faust(faust_voice_faust* RESTRICT dsp) {
	return 0;
}
int getNumOutputsfaust_voice_faust(faust_voice_faust* RESTRICT dsp) {
	return 2;
}

void classInitfaust_voice_faust(int sample_rate) {
}

void instanceResetUserInterfacefaust_voice_faust(faust_voice_faust* dsp) {
	dsp->fHslider0 = (FAUSTFLOAT)(0.7f);
	dsp->fHslider1 = (FAUSTFLOAT)(0.3f);
	dsp->fHslider2 = (FAUSTFLOAT)(0.6f);
	dsp->fHslider3 = (FAUSTFLOAT)(0.8f);
	dsp->fHslider4 = (FAUSTFLOAT)(2.2e+02f);
	dsp->fHslider5 = (FAUSTFLOAT)(0.01f);
	dsp->fHslider6 = (FAUSTFLOAT)(0.0f);
	dsp->fHslider7 = (FAUSTFLOAT)(0.3f);
}

void instanceClearfaust_voice_faust(faust_voice_faust* dsp) {
	/* C99 loop */
	{
		int l0;
		for (l0 = 0; l0 < 2; l0 = l0 + 1) {
			dsp->fRec1[l0] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l1;
		for (l1 = 0; l1 < 2; l1 = l1 + 1) {
			dsp->fVec0[l1] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l2;
		for (l2 = 0; l2 < 2; l2 = l2 + 1) {
			dsp->fRec3[l2] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l3;
		for (l3 = 0; l3 < 2; l3 = l3 + 1) {
			dsp->iRec4[l3] = 0;
		}
	}
	/* C99 loop */
	{
		int l4;
		for (l4 = 0; l4 < 3; l4 = l4 + 1) {
			dsp->fRec0[l4] = 0.0f;
		}
	}
}

void instanceConstantsfaust_voice_faust(faust_voice_faust* dsp, int sample_rate) {
	dsp->fSampleRate = sample_rate;
	dsp->fConst0 = fminf(1.92e+05f, fmaxf(1.0f, (float)(dsp->fSampleRate)));
	dsp->fConst1 = 188.49556f / dsp->fConst0;
	dsp->fConst2 = 1.0f / dsp->fConst0;
}
	
void instanceInitfaust_voice_faust(faust_voice_faust* dsp, int sample_rate) {
	instanceConstantsfaust_voice_faust(dsp, sample_rate);
	instanceResetUserInterfacefaust_voice_faust(dsp);
	instanceClearfaust_voice_faust(dsp);
}

void initfaust_voice_faust(faust_voice_faust* dsp, int sample_rate) {
	classInitfaust_voice_faust(sample_rate);
	instanceInitfaust_voice_faust(dsp, sample_rate);
}

void buildUserInterfacefaust_voice_faust(faust_voice_faust* dsp, UIGlue* ui_interface) {
	ui_interface->openVerticalBox(ui_interface->uiInterface, "faust_voice");
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "attack", &dsp->fHslider5, (FAUSTFLOAT)0.01f, (FAUSTFLOAT)0.001f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.001f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "cutoff", &dsp->fHslider2, (FAUSTFLOAT)0.6f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "freq", &dsp->fHslider4, (FAUSTFLOAT)2.2e+02f, (FAUSTFLOAT)16.0f, (FAUSTFLOAT)12544.0f, (FAUSTFLOAT)0.001f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "gain", &dsp->fHslider3, (FAUSTFLOAT)0.8f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.001f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "gate", &dsp->fHslider6, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)1.0f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "level", &dsp->fHslider0, (FAUSTFLOAT)0.7f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "release", &dsp->fHslider7, (FAUSTFLOAT)0.3f, (FAUSTFLOAT)0.01f, (FAUSTFLOAT)4.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "resonance", &dsp->fHslider1, (FAUSTFLOAT)0.3f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->closeBox(ui_interface->uiInterface);
}

void computefaust_voice_faust(faust_voice_faust* dsp, int count, FAUSTFLOAT** RESTRICT inputs, FAUSTFLOAT** RESTRICT outputs) {
	FAUSTFLOAT* output0 = outputs[0];
	FAUSTFLOAT* output1 = outputs[1];
	float fSlow0 = (float)(dsp->fHslider0);
	float fSlow1 = 1.0f / (17.5f * (float)(dsp->fHslider1) + 0.5f);
	float fSlow2 = tanf(dsp->fConst1 * powf(233.33333f, (float)(dsp->fHslider2)));
	float fSlow3 = 1.0f / fSlow2;
	float fSlow4 = 1.0f / ((fSlow1 + fSlow3) / fSlow2 + 1.0f);
	float fSlow5 = (float)(dsp->fHslider3);
	float fSlow6 = fmaxf(1.1920929e-07f, fabsf((float)(dsp->fHslider4)));
	float fSlow7 = dsp->fConst2 * fSlow6;
	float fSlow8 = 1.0f - dsp->fConst0 / fSlow6;
	float fSlow9 = 1.0f / fmaxf(1.0f, dsp->fConst0 * (float)(dsp->fHslider5));
	float fSlow10 = (float)(dsp->fHslider6);
	float fSlow11 = 1.0f / fmaxf(1.0f, dsp->fConst0 * (float)(dsp->fHslider7));
	int iSlow12 = fSlow10 == 0.0f;
	float fSlow13 = (fSlow3 - fSlow1) / fSlow2 + 1.0f;
	float fSlow14 = 2.0f * (1.0f - 1.0f / faust_voice_faust_faustpower2_f(fSlow2));
	/* C99 loop */
	{
		int i0;
		for (i0 = 0; i0 < count; i0 = i0 + 1) {
			float fTemp0 = fSlow7 + dsp->fRec1[1] + -1.0f;
			int iTemp1 = fTemp0 < 0.0f;
			float fTemp2 = fSlow7 + dsp->fRec1[1];
			dsp->fRec1[0] = ((iTemp1) ? fTemp2 : fTemp0);
			float fRec2 = ((iTemp1) ? fTemp2 : fSlow7 + dsp->fRec1[1] + fSlow8 * fTemp0);
			dsp->fVec0[0] = fSlow10;
			dsp->fRec3[0] = fSlow10 + dsp->fRec3[1] * (float)(dsp->fVec0[1] >= fSlow10);
			dsp->iRec4[0] = iSlow12 * (dsp->iRec4[1] + 1);
			dsp->fRec0[0] = fSlow5 * (2.0f * fRec2 + -1.0f) * fmaxf(0.0f, fminf(fSlow9 * dsp->fRec3[0], 1.0f) * (1.0f - fSlow11 * (float)(dsp->iRec4[0]))) - fSlow4 * (fSlow13 * dsp->fRec0[2] + fSlow14 * dsp->fRec0[1]);
			float fTemp3 = fSlow0 * tanhf(fSlow4 * (dsp->fRec0[2] + dsp->fRec0[0] + 2.0f * dsp->fRec0[1]));
			output0[i0] = (FAUSTFLOAT)(fTemp3);
			output1[i0] = (FAUSTFLOAT)(fTemp3);
			dsp->fRec1[1] = dsp->fRec1[0];
			dsp->fVec0[1] = dsp->fVec0[0];
			dsp->fRec3[1] = dsp->fRec3[0];
			dsp->iRec4[1] = dsp->iRec4[0];
			dsp->fRec0[2] = dsp->fRec0[1];
			dsp->fRec0[1] = dsp->fRec0[0];
		}
	}
}

#ifdef __cplusplus
}
#endif

#endif
