/* GENERATED by scripts/gen-faust.ts from faust_voice.dsp via Faust */
/* Regenerate with: mise run gen-faust (or: pnpm run gen-faust) */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"

/* ------------------------------------------------------------
name: "faust_voice"
Code generated with Faust 2.85.5 (https://faust.grame.fr)
Compilation options: -a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn faust_voice_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */

#ifndef  __faust_voice_faust_H__
#define  __faust_voice_faust_H__

/* Faust architecture file: library-only output.
 *
 * Used by scripts/gen-faust.ts to generate the per-module C from a .dsp
 * source. Produces only the DSP class definitions (struct + functions like
 * `new<prefix>`, `init<prefix>`, `compute<prefix>`, `buildUserInterface<prefix>`)
 * with no `main()`. The moveforge per-module adapter
 * (`<id>_core.c`) consumes that output.
 *
 * Faust replaces <<includeIntrinsic>> and <<includeclass>> at codegen time.
 * Keep this file small and dependency-light so the generated artifact stays
 * portable and drops cleanly into the existing Schwung wrapper pipeline.
 */

#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif

/* The generated `buildUserInterface` walks a UIGlue struct of callbacks.
 * We don't use Faust's UI to discover params at runtime — the moveforge
 * adapter knows param indices statically — so we provide a stub type
 * that satisfies the symbol without pulling in Faust's UI runtime. */
typedef struct UIGlue UIGlue;
typedef struct MetaGlue MetaGlue;


#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 


#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

/* link with : "" */
#include <math.h>
#include <stdint.h>
#include <stdlib.h>

static float faust_voice_faust_faustpower2_f(float value) {
	return value * value;
}

#ifndef FAUSTCLASS 
#define FAUSTCLASS faust_voice_faust
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif
#ifndef FAUSTMAXI
#define FAUSTMAXI
inline int faustmaxi(int a, int b) { return (a > b) ? a : b; }
inline int faustmini(int a, int b) { return (a < b) ? a : b; }
#endif

typedef struct {
	FAUSTFLOAT fHslider0;
	float fVec0[2];
	FAUSTFLOAT fHslider1;
	int fSampleRate;
	float fConst0;
	float fConst1;
	FAUSTFLOAT fHslider2;
	FAUSTFLOAT fHslider3;
	float fConst2;
	FAUSTFLOAT fHslider4;
	float fRec2[2];
	FAUSTFLOAT fHslider5;
	FAUSTFLOAT fHslider6;
	float fVec1[2];
	float fRec4[2];
	FAUSTFLOAT fHslider7;
	int iRec5[2];
	float fRec1[3];
	float fVec2[2];
	float fRec0[2];
	float fConst3;
	float fRec6[2];
} faust_voice_faust;

faust_voice_faust* newfaust_voice_faust() { 
	faust_voice_faust* dsp = (faust_voice_faust*)calloc(1, sizeof(faust_voice_faust));
	return dsp;
}

void deletefaust_voice_faust(faust_voice_faust* dsp) { 
	free(dsp);
}

void metadatafaust_voice_faust(MetaGlue* m) { 
	m->declare(m->metaInterface, "basics.lib/name", "Faust Basic Element Library");
	m->declare(m->metaInterface, "basics.lib/version", "1.22.0");
	m->declare(m->metaInterface, "compile_options", "-a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn faust_voice_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
	m->declare(m->metaInterface, "envelopes.lib/adsr:author", "Yann Orlarey and Andrey Bundin");
	m->declare(m->metaInterface, "envelopes.lib/author", "GRAME");
	m->declare(m->metaInterface, "envelopes.lib/copyright", "GRAME");
	m->declare(m->metaInterface, "envelopes.lib/license", "LGPL with exception");
	m->declare(m->metaInterface, "envelopes.lib/name", "Faust Envelope Library");
	m->declare(m->metaInterface, "envelopes.lib/version", "1.3.0");
	m->declare(m->metaInterface, "filename", "faust_voice.dsp");
	m->declare(m->metaInterface, "filters.lib/dcblocker:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/dcblocker:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/dcblocker:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/fir:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/fir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/fir:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/iir:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/iir:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/iir:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/name", "Faust Filters Library");
	m->declare(m->metaInterface, "filters.lib/pole:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/pole:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/pole:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/resonlp:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/resonlp:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/resonlp:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/tf2:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/tf2:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/tf2:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/tf2s:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/tf2s:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/tf2s:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/version", "1.7.1");
	m->declare(m->metaInterface, "filters.lib/zero:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/zero:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/zero:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "maths.lib/author", "GRAME");
	m->declare(m->metaInterface, "maths.lib/copyright", "GRAME");
	m->declare(m->metaInterface, "maths.lib/license", "LGPL with exception");
	m->declare(m->metaInterface, "maths.lib/name", "Faust Math Library");
	m->declare(m->metaInterface, "maths.lib/version", "2.9.0");
	m->declare(m->metaInterface, "moveforge.lib/author", "moveforge");
	m->declare(m->metaInterface, "moveforge.lib/name", "moveforge");
	m->declare(m->metaInterface, "name", "faust_voice");
	m->declare(m->metaInterface, "oscillators.lib/name", "Faust Oscillator Library");
	m->declare(m->metaInterface, "oscillators.lib/saw2ptr:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "oscillators.lib/saw2ptr:license", "STK-4.3");
	m->declare(m->metaInterface, "oscillators.lib/version", "1.7.0");
	m->declare(m->metaInterface, "platform.lib/name", "Generic Platform Library");
	m->declare(m->metaInterface, "platform.lib/version", "1.3.0");
	m->declare(m->metaInterface, "signals.lib/name", "Faust Routing Library");
	m->declare(m->metaInterface, "signals.lib/version", "1.6.0");
}

int getSampleRatefaust_voice_faust(faust_voice_faust* RESTRICT dsp) {
	return dsp->fSampleRate;
}

int getNumInputsfaust_voice_faust(faust_voice_faust* RESTRICT dsp) {
	return 0;
}
int getNumOutputsfaust_voice_faust(faust_voice_faust* RESTRICT dsp) {
	return 2;
}

void classInitfaust_voice_faust(int sample_rate) {
}

void instanceResetUserInterfacefaust_voice_faust(faust_voice_faust* dsp) {
	dsp->fHslider0 = (FAUSTFLOAT)(0.7f);
	dsp->fHslider1 = (FAUSTFLOAT)(0.3f);
	dsp->fHslider2 = (FAUSTFLOAT)(0.6f);
	dsp->fHslider3 = (FAUSTFLOAT)(0.8f);
	dsp->fHslider4 = (FAUSTFLOAT)(2.2e+02f);
	dsp->fHslider5 = (FAUSTFLOAT)(0.01f);
	dsp->fHslider6 = (FAUSTFLOAT)(0.0f);
	dsp->fHslider7 = (FAUSTFLOAT)(0.3f);
}

void instanceClearfaust_voice_faust(faust_voice_faust* dsp) {
	/* C99 loop */
	{
		int l0;
		for (l0 = 0; l0 < 2; l0 = l0 + 1) {
			dsp->fVec0[l0] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l1;
		for (l1 = 0; l1 < 2; l1 = l1 + 1) {
			dsp->fRec2[l1] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l2;
		for (l2 = 0; l2 < 2; l2 = l2 + 1) {
			dsp->fVec1[l2] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l3;
		for (l3 = 0; l3 < 2; l3 = l3 + 1) {
			dsp->fRec4[l3] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l4;
		for (l4 = 0; l4 < 2; l4 = l4 + 1) {
			dsp->iRec5[l4] = 0;
		}
	}
	/* C99 loop */
	{
		int l5;
		for (l5 = 0; l5 < 3; l5 = l5 + 1) {
			dsp->fRec1[l5] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l6;
		for (l6 = 0; l6 < 2; l6 = l6 + 1) {
			dsp->fVec2[l6] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l7;
		for (l7 = 0; l7 < 2; l7 = l7 + 1) {
			dsp->fRec0[l7] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l8;
		for (l8 = 0; l8 < 2; l8 = l8 + 1) {
			dsp->fRec6[l8] = 0.0f;
		}
	}
}

void instanceConstantsfaust_voice_faust(faust_voice_faust* dsp, int sample_rate) {
	dsp->fSampleRate = sample_rate;
	dsp->fConst0 = fminf(1.92e+05f, fmaxf(1.0f, (float)(dsp->fSampleRate)));
	dsp->fConst1 = 188.49556f / dsp->fConst0;
	dsp->fConst2 = 1.0f / dsp->fConst0;
	dsp->fConst3 = expf(-(5e+01f / dsp->fConst0));
}
	
void instanceInitfaust_voice_faust(faust_voice_faust* dsp, int sample_rate) {
	instanceConstantsfaust_voice_faust(dsp, sample_rate);
	instanceResetUserInterfacefaust_voice_faust(dsp);
	instanceClearfaust_voice_faust(dsp);
}

void initfaust_voice_faust(faust_voice_faust* dsp, int sample_rate) {
	classInitfaust_voice_faust(sample_rate);
	instanceInitfaust_voice_faust(dsp, sample_rate);
}

void buildUserInterfacefaust_voice_faust(faust_voice_faust* dsp, UIGlue* ui_interface) {
	ui_interface->openVerticalBox(ui_interface->uiInterface, "faust_voice");
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "attack", &dsp->fHslider5, (FAUSTFLOAT)0.01f, (FAUSTFLOAT)0.001f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.001f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "cutoff", &dsp->fHslider2, (FAUSTFLOAT)0.6f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "freq", &dsp->fHslider4, (FAUSTFLOAT)2.2e+02f, (FAUSTFLOAT)16.0f, (FAUSTFLOAT)12544.0f, (FAUSTFLOAT)0.001f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "gain", &dsp->fHslider3, (FAUSTFLOAT)0.8f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.001f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "gate", &dsp->fHslider6, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)1.0f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "level", &dsp->fHslider0, (FAUSTFLOAT)0.7f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "release", &dsp->fHslider7, (FAUSTFLOAT)0.3f, (FAUSTFLOAT)0.01f, (FAUSTFLOAT)4.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "resonance", &dsp->fHslider1, (FAUSTFLOAT)0.3f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->closeBox(ui_interface->uiInterface);
}

void computefaust_voice_faust(faust_voice_faust* dsp, int count, FAUSTFLOAT** RESTRICT inputs, FAUSTFLOAT** RESTRICT outputs) {
	FAUSTFLOAT* output0 = outputs[0];
	FAUSTFLOAT* output1 = outputs[1];
	float fSlow0 = (float)(dsp->fHslider0);
	float fSlow1 = 0.65f * (float)(fSlow0 > 0.0f);
	float fSlow2 = 1.0f / (17.5f * (float)(dsp->fHslider1) + 0.5f);
	float fSlow3 = tanf(dsp->fConst1 * powf(233.33333f, (float)(dsp->fHslider2)));
	float fSlow4 = 1.0f / fSlow3;
	float fSlow5 = 1.0f / ((fSlow2 + fSlow4) / fSlow3 + 1.0f);
	float fSlow6 = (float)(dsp->fHslider3);
	float fSlow7 = fmaxf(1.1920929e-07f, fabsf((float)(dsp->fHslider4)));
	float fSlow8 = dsp->fConst2 * fSlow7;
	float fSlow9 = 1.0f - dsp->fConst0 / fSlow7;
	float fSlow10 = 1.0f / fmaxf(1.0f, dsp->fConst0 * (float)(dsp->fHslider5));
	float fSlow11 = (float)(dsp->fHslider6);
	float fSlow12 = 1.0f / fmaxf(1.0f, dsp->fConst0 * (float)(dsp->fHslider7));
	int iSlow13 = fSlow11 == 0.0f;
	float fSlow14 = (fSlow4 - fSlow2) / fSlow3 + 1.0f;
	float fSlow15 = 2.0f * (1.0f - 1.0f / faust_voice_faust_faustpower2_f(fSlow3));
	/* C99 loop */
	{
		int i0;
		for (i0 = 0; i0 < count; i0 = i0 + 1) {
			dsp->fVec0[0] = 1.0f;
			float fTemp0 = fSlow8 + dsp->fRec2[1] + -1.0f;
			int iTemp1 = fTemp0 < 0.0f;
			float fTemp2 = fSlow8 + dsp->fRec2[1];
			float fTemp3 = ((iTemp1) ? fTemp2 : fTemp0);
			dsp->fRec2[0] = ((fabsf(fTemp3) > 1.1754944e-38f) ? fTemp3 : 0.0f);
			float fTemp4 = ((iTemp1) ? fTemp2 : fSlow8 + dsp->fRec2[1] + fSlow9 * fTemp0);
			float fRec3 = ((fabsf(fTemp4) > 1.1754944e-38f) ? fTemp4 : 0.0f);
			dsp->fVec1[0] = fSlow11;
			float fTemp5 = fSlow11 + dsp->fRec4[1] * (float)(dsp->fVec1[1] >= fSlow11);
			dsp->fRec4[0] = ((fabsf(fTemp5) > 1.1754944e-38f) ? fTemp5 : 0.0f);
			dsp->iRec5[0] = iSlow13 * (dsp->iRec5[1] + 1);
			float fTemp6 = fSlow6 * (2.0f * fRec3 + -1.0f) * fmaxf(0.0f, fminf(fSlow10 * dsp->fRec4[0], 1.0f) * (1.0f - fSlow12 * (float)(dsp->iRec5[0]))) - fSlow5 * (fSlow14 * dsp->fRec1[2] + fSlow15 * dsp->fRec1[1]);
			dsp->fRec1[0] = ((fabsf(fTemp6) > 1.1754944e-38f) ? fTemp6 : 0.0f);
			float fTemp7 = tanhf(fSlow5 * (dsp->fRec1[2] + dsp->fRec1[0] + 2.0f * dsp->fRec1[1]));
			dsp->fVec2[0] = fTemp7;
			float fTemp8 = 0.995f * dsp->fRec0[1] + fTemp7 - dsp->fVec2[1];
			dsp->fRec0[0] = ((fabsf(fTemp8) > 1.1754944e-38f) ? fTemp8 : 0.0f);
			float fTemp9 = fSlow0 * (1.0f - dsp->fConst3 * dsp->fVec0[1]) + dsp->fConst3 * dsp->fVec0[1] * dsp->fRec6[1];
			dsp->fRec6[0] = ((fabsf(fTemp9) > 1.1754944e-38f) ? fTemp9 : 0.0f);
			float fTemp10 = fSlow1 * dsp->fRec0[0] * dsp->fRec6[0];
			output0[i0] = (FAUSTFLOAT)(fTemp10);
			output1[i0] = (FAUSTFLOAT)(fTemp10);
			dsp->fVec0[1] = dsp->fVec0[0];
			dsp->fRec2[1] = dsp->fRec2[0];
			dsp->fVec1[1] = dsp->fVec1[0];
			dsp->fRec4[1] = dsp->fRec4[0];
			dsp->iRec5[1] = dsp->iRec5[0];
			dsp->fRec1[2] = dsp->fRec1[1];
			dsp->fRec1[1] = dsp->fRec1[0];
			dsp->fVec2[1] = dsp->fVec2[0];
			dsp->fRec0[1] = dsp->fRec0[0];
			dsp->fRec6[1] = dsp->fRec6[0];
		}
	}
}

#ifdef __cplusplus
}
#endif

#endif

#pragma GCC diagnostic pop
