/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of faust_voice_params.gen.inc so the param count and enum are
 * visible to faust_voice_core.h, which needs FAUST_VOICE_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking faust_voice_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef FAUST_VOICE_PARAMS_GEN_H
#define FAUST_VOICE_PARAMS_GEN_H

#define FAUST_VOICE_PARAM_COUNT 5

enum {
    FAUST_VOICE_PARAM_CUTOFF = 0,
    FAUST_VOICE_PARAM_RESONANCE = 1,
    FAUST_VOICE_PARAM_ATTACK = 2,
    FAUST_VOICE_PARAM_RELEASE = 3,
    FAUST_VOICE_PARAM_LEVEL = 4
};

#endif
