/*
 * Faust Voice Chain UI — GENERATED by scripts/gen-ui-chain.ts from module.json.
 * Do not edit by hand: change module.json and re-run `mise run gen-ui-chain`.
 *
 * Scrollable parameter editor shown when this module is opened (wheel press)
 * in a chain slot. Top knobs (Knob 1..6) adjust the visible params; the
 * jog wheel scrolls when there are more than 6. Sets globalThis.chain_ui.
 */

import {
    MoveMainKnob,
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4, MoveKnob5, MoveKnob6
} from '/data/UserData/schwung/shared/constants.mjs';

import { decodeDelta } from '/data/UserData/schwung/shared/input_filter.mjs';

import { drawMenuHeader as drawHeader } from '/data/UserData/schwung/shared/menu_layout.mjs';

const SCREEN_WIDTH = 128;
const KNOBS = [MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4, MoveKnob5, MoveKnob6];

const PARAMS = [
    { key: "cutoff", name: "Cutoff", min: 0, max: 1, step: 0.01, dec: 2, def: 0.6 },
    { key: "resonance", name: "Resonance", min: 0, max: 1, step: 0.01, dec: 2, def: 0.3 },
    { key: "attack", name: "Attack", min: 0.001, max: 1, step: 0.01998, dec: 2, def: 0.01 },
    { key: "release", name: "Release", min: 0.01, max: 4, step: 0.0798, dec: 2, def: 0.3 },
    { key: "level", name: "Level", min: 0, max: 1, step: 0.01, dec: 2, def: 0.7 }
];

const VISIBLE = Math.min(PARAMS.length, 6);
const LIST_Y = 14;
const LINE_H = 8;
const MAX_SCROLL = Math.max(0, PARAMS.length - VISIBLE);

let scrollTop = 0;
let paramValues = PARAMS.map((p) => p.def);
let needsRedraw = true;

function clampScroll(v) {
    return Math.max(0, Math.min(MAX_SCROLL, v));
}

function fetchParams() {
    for (let i = 0; i < PARAMS.length; i++) {
        const val = host_module_get_param(PARAMS[i].key);
        if (val !== null && val !== undefined) {
            const f = parseFloat(val);
            if (!isNaN(f)) paramValues[i] = f;
        }
    }
}

function setParam(index, value) {
    const param = PARAMS[index];
    value = Math.max(param.min, Math.min(param.max, value));
    paramValues[index] = value;
    host_module_set_param(param.key, value.toFixed(2));
}

function adjustParam(index, delta) {
    setParam(index, paramValues[index] + delta * PARAMS[index].step);
    needsRedraw = true;
}

function drawUI() {
    clear_screen();
    drawHeader("Faust Voice");

    const end = Math.min(scrollTop + VISIBLE, PARAMS.length);
    for (let i = scrollTop; i < end; i++) {
        const y = LIST_Y + (i - scrollTop) * LINE_H;
        const param = PARAMS[i];
        print(2, y, param.name, 1);
        const valueStr = paramValues[i].toFixed(param.dec);
        print(SCREEN_WIDTH - valueStr.length * 6 - 8, y, valueStr, 1);
    }

    /* Scroll indicators when the list overflows the screen. */
    if (scrollTop > 0) print(SCREEN_WIDTH - 6, LIST_Y, "^", 1);
    if (end < PARAMS.length) print(SCREEN_WIDTH - 6, LIST_Y + (VISIBLE - 1) * LINE_H, "v", 1);

    needsRedraw = false;
}

function init() {
    fetchParams();
    scrollTop = 0;
    needsRedraw = true;
}

function tick() {
    if (needsRedraw) drawUI();
}

function onMidiMessageInternal(data) {
    const status = data[0];
    const d1 = data[1];
    const d2 = data[2];
    if ((status & 0xF0) !== 0xB0) return;

    /* Jog wheel scrolls the visible window. */
    if (d1 === MoveMainKnob) {
        const delta = decodeDelta(d2);
        if (delta !== 0) {
            const next = clampScroll(scrollTop + delta);
            if (next !== scrollTop) { scrollTop = next; needsRedraw = true; }
        }
        return;
    }

    /* Each visible row is adjusted by its corresponding top knob. */
    for (let k = 0; k < VISIBLE; k++) {
        if (d1 === KNOBS[k]) {
            const delta = decodeDelta(d2);
            if (delta !== 0) adjustParam(scrollTop + k, delta);
            return;
        }
    }
}

globalThis.chain_ui = {
    init,
    tick,
    onMidiMessageInternal
};
