/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of vca_params.gen.inc so the param count and enum are
 * visible to vca_core.h, which needs VCA_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking vca_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef VCA_PARAMS_GEN_H
#define VCA_PARAMS_GEN_H

#define VCA_PARAM_COUNT 4

enum {
    VCA_PARAM_ATTACK = 0,
    VCA_PARAM_DECAY = 1,
    VCA_PARAM_SUSTAIN = 2,
    VCA_PARAM_RELEASE = 3
};

#endif
