/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of ballast_params.gen.inc so the param count and enum are
 * visible to ballast_core.h, which needs BALLAST_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking ballast_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef BALLAST_PARAMS_GEN_H
#define BALLAST_PARAMS_GEN_H

#define BALLAST_PARAM_COUNT 16

enum {
    BALLAST_PARAM_TUNE = 0,
    BALLAST_PARAM_PUNCH = 1,
    BALLAST_PARAM_DROP = 2,
    BALLAST_PARAM_DECAY = 3,
    BALLAST_PARAM_DRIVE = 4,
    BALLAST_PARAM_TONE = 5,
    BALLAST_PARAM_DIRT = 6,
    BALLAST_PARAM_VOLUME = 7,
    BALLAST_PARAM_TRACK = 8,
    BALLAST_PARAM_SWEEP = 9,
    BALLAST_PARAM_SHAPE = 10,
    BALLAST_PARAM_PHASE = 11,
    BALLAST_PARAM_CURVE = 12,
    BALLAST_PARAM_BODY = 13,
    BALLAST_PARAM_VEL_DEPTH = 14,
    BALLAST_PARAM_HUMAN = 15
};

#endif
