/*
 * Ballast Chain UI — GENERATED by scripts/gen-ui-chain.ts from module.json.
 * Do not edit by hand: change module.json and re-run `mise run gen-ui-chain`.
 *
 * Scrollable parameter editor shown when this module is opened (wheel press)
 * in a chain slot. Knob 1..8 adjust the active encoder bank
 * declared by module.json's root.knobs order, and the jog wheel
 * scrolls/selects/edits focused rows. Press the Encoder Bank row to switch banks.
 * Sets globalThis.chain_ui.
 */

import {
    MidiNoteOff, MidiNoteOn,
    MoveMainButton, MoveMainKnob,
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4,
    MoveKnob5, MoveKnob6, MoveKnob7, MoveKnob8,
    MoveKnob1Touch, MoveKnob2Touch, MoveKnob3Touch, MoveKnob4Touch,
    MoveKnob5Touch, MoveKnob6Touch, MoveKnob7Touch, MoveKnob8Touch
} from '/data/UserData/schwung/shared/constants.mjs';

import { decodeDelta } from '/data/UserData/schwung/shared/input_filter.mjs';

import {
    drawMenuFooter as drawFooter,
    drawMenuHeader as drawHeader,
    drawOverlay,
    drawMenuList,
    FOOTER_RULE_Y,
    LIST_TOP_Y,
    hideOverlay,
    showOverlay,
    tickOverlay
} from '/data/UserData/schwung/shared/menu_layout.mjs';

const ENCODER_COUNT = 8;
const KNOBS = [
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4,
    MoveKnob5, MoveKnob6, MoveKnob7, MoveKnob8
];

const KNOB_TOUCHES = [
    MoveKnob1Touch, MoveKnob2Touch, MoveKnob3Touch, MoveKnob4Touch,
    MoveKnob5Touch, MoveKnob6Touch, MoveKnob7Touch, MoveKnob8Touch
];

const PARAMS = [
    { key: "tune", name: "Tune", min: 24, max: 72, step: 0.48, dec: 1, def: 33 },
    { key: "punch", name: "Punch", min: 0, max: 1, step: 0.01, dec: 2, def: 0.5 },
    { key: "drop", name: "Drop", min: 0, max: 1, step: 0.01, dec: 2, def: 0.45 },
    { key: "decay", name: "Decay", min: 0.05, max: 3, step: 0.0295, dec: 2, def: 0.45 },
    { key: "drive", name: "Drive", min: 0, max: 1, step: 0.01, dec: 2, def: 0.3 },
    { key: "tone", name: "Tone", min: 0, max: 1, step: 0.01, dec: 2, def: 0.5 },
    { key: "dirt", name: "Dirt", min: 0, max: 1, step: 0.01, dec: 2, def: 0 },
    { key: "volume", name: "Volume", min: 0, max: 1, step: 0.01, dec: 2, def: 0.75 },
    { key: "track", name: "Track", min: 0, max: 1, step: 0.01, dec: 2, def: 0 },
    { key: "sweep", name: "Sweep", min: 0, max: 1, step: 0.01, dec: 2, def: 0.45 },
    { key: "shape", name: "Shape", min: 0, max: 1, step: 0.01, dec: 2, def: 0.35 },
    { key: "phase", name: "Phase", min: 0, max: 1, step: 0.01, dec: 2, def: 0 },
    { key: "curve", name: "Curve", min: 0, max: 4, step: 1, dec: 0, def: 0 },
    { key: "body", name: "Body", min: 0, max: 1, step: 0.01, dec: 2, def: 0.2 },
    { key: "vel_depth", name: "Vel Depth", min: 0, max: 1, step: 0.01, dec: 2, def: 0.6 },
    { key: "human", name: "Human", min: 0, max: 1, step: 0.01, dec: 2, def: 0 }
];

const KNOB_PARAM_INDEXES = [
    0,
    1,
    2,
    3,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15
];

let selectedIndex = 0;
let paramValues = PARAMS.map((p) => p.def);
let presetCount = 0;
let presetIndex = 0;
let presetName = "";
let mode = "params";
let editMode = false;
let encoderPage = 0;
let needsRedraw = true;

// Optional oscilloscope: if the DSP serves a non-empty "__scope" frame
// (src/modules/_shared/scope.h), flash the captured attack waveform when a new
// frame arrives (i.e. on each note). Modules without scope return null here, so
// all of this stays a no-op for them. Frame format: 2 chars/column, max-row
// then min-row, each 0..63 offset by 48.
const SCOPE_ENC_BASE = 48;
const SCOPE_VAL_ROWS = 64;
const SCOPE_POLL_TICKS = 4;     // poll cadence (robust to the chain UI tick rate)
const SCOPE_LINGER_POLLS = 2;   // empty polls before hiding -> brief post-release linger
const SCOPE_HINT_POLLS = 4;     // param-readout linger (polls) while the scope is up
let scopeData = "";
let scopeVisible = false;
let scopeEmptyPolls = 0;
let scopePollDiv = 0;
let paramHintText = "";
let paramHintHold = 0;

function clampSelected(v) {
    return Math.max(0, Math.min(Math.max(0, displayItemCount() - 1), v));
}

function hasEncoderBankRow() {
    return pageCount() > 1;
}

function displayItemCount() {
    return hasEncoderBankRow() ? (1 + bankParamIndexes().length) : PARAMS.length;
}

function selectedParamIndex() {
    if (hasEncoderBankRow()) {
        if (selectedIndex === 0) return -1;
        return bankParamIndexes()[selectedIndex - 1] ?? -1;
    }
    return selectedIndex;
}

function displayIndexForParam(paramIndex) {
    if (!hasEncoderBankRow()) return paramIndex;
    const slot = bankParamIndexes().indexOf(paramIndex);
    if (slot >= 0) return slot + 1;
    return 0;
}

function displayItems() {
    if (!hasEncoderBankRow()) return PARAMS;
    return [{ bank: true, name: "Encoder Bank" }, ...bankParamIndexes().map((index) => PARAMS[index])];
}

function isBankRow(index) {
    return hasEncoderBankRow() && index === 0;
}

function pageCount() {
    return Math.max(1, Math.ceil(Math.max(1, KNOB_PARAM_INDEXES.length) / ENCODER_COUNT));
}

function clampPage(v) {
    return Math.max(0, Math.min(pageCount() - 1, v));
}

function wrapPage(v) {
    const count = pageCount();
    return ((v % count) + count) % count;
}

function pageStart() {
    return encoderPage * ENCODER_COUNT;
}

function bankParamIndexes() {
    const start = pageStart();
    return KNOB_PARAM_INDEXES.slice(start, start + ENCODER_COUNT).filter((index) => index !== undefined && index < PARAMS.length);
}

function pageLabel() {
    return String(encoderPage + 1) + "/" + String(pageCount());
}

function selectIndex(index) {
    selectedIndex = clampSelected(index);
    editMode = false;
    needsRedraw = true;
}

function setEncoderPage(page) {
    const next = clampPage(page);
    if (next === encoderPage) return;
    encoderPage = next;
    selectedIndex = 0;
    needsRedraw = true;
}

function fetchParams() {
    for (let i = 0; i < PARAMS.length; i++) {
        fetchParam(i);
    }
}

function fetchParam(index) {
    if (index < 0 || index >= PARAMS.length) return;
    const val = host_module_get_param(PARAMS[index].key);
    if (val !== null && val !== undefined) {
        const f = parseFloat(val);
        if (!isNaN(f)) paramValues[index] = f;
    }
}

function fetchPreset() {
    const count = host_module_get_param("preset_count");
    const parsedCount = count !== null && count !== undefined ? parseInt(count) : 0;
    presetCount = isNaN(parsedCount) ? 0 : Math.max(0, parsedCount);

    const preset = host_module_get_param("preset");
    const parsedPreset = preset !== null && preset !== undefined ? parseInt(preset) : 0;
    presetIndex = isNaN(parsedPreset) ? 0 : Math.max(0, Math.min(Math.max(0, presetCount - 1), parsedPreset));

    presetName = host_module_get_param("preset_name") || "";
}

function setParam(index, value) {
    const param = PARAMS[index];
    value = Math.max(param.min, Math.min(param.max, value));
    paramValues[index] = value;
    host_module_set_param(param.key, value.toFixed(2));
}

function adjustParam(index, delta) {
    setParam(index, paramValues[index] + delta * PARAMS[index].step);
    needsRedraw = true;
}

function encoderParamIndex(k) {
    const knobIndex = pageStart() + k;
    return KNOB_PARAM_INDEXES[knobIndex];
}

function formatParamValue(index) {
    fetchParam(index);
    return paramValues[index].toFixed(PARAMS[index].dec);
}

function showEncoderOverlay(k, paramIndex) {
    // While the scope is up, show a compact one-line readout over the waveform
    // instead of the big centred box, so dialing a knob keeps the waveform
    // visible (watch the sound change as you turn). Otherwise use the box.
    if (scopeVisible && paramIndex !== undefined && paramIndex < PARAMS.length) {
        paramHintText = PARAMS[paramIndex].name + " " + formatParamValue(paramIndex);
        paramHintHold = SCOPE_HINT_POLLS;
    } else if (paramIndex !== undefined && paramIndex < PARAMS.length) {
        showOverlay("K" + String(k + 1) + " " + PARAMS[paramIndex].name, formatParamValue(paramIndex));
    } else {
        showOverlay("K" + String(k + 1), "Unmapped");
    }
    needsRedraw = true;
}

function changePreset(delta) {
    if (presetCount <= 0) return;
    let next = presetIndex + delta;
    if (next < 0) next = presetCount - 1;
    if (next >= presetCount) next = 0;
    presetIndex = next;
    host_module_set_param("preset", String(presetIndex));
    fetchPreset();
    fetchParams();
    needsRedraw = true;
}

function toggleMode() {
    if (presetCount <= 0) return;
    mode = mode === "preset" ? "params" : "preset";
    editMode = false;
    needsRedraw = true;
}

function toggleEncoderPage() {
    if (mode !== "params" || pageCount() <= 1) return;
    setEncoderPage(wrapPage(encoderPage + 1));
}

function toggleEditMode() {
    if (mode !== "params" || PARAMS.length === 0) return;
    if (isBankRow(selectedIndex)) {
        toggleEncoderPage();
        return;
    }
    editMode = !editMode;
    needsRedraw = true;
}

function drawCentered(y, text) {
    const s = String(text || "");
    const x = Math.max(0, Math.floor((128 - s.length * 5) / 2));
    print(x, y, s, 1);
}

function drawPresetUI() {
    clear_screen();
    drawHeader("Ballast");

    fetchPreset();
    if (presetCount > 0) {
        drawCentered(24, String(presetIndex + 1) + " / " + String(presetCount));
        drawCentered(36, presetName || "Preset " + String(presetIndex + 1));
        print(4, 32, "<", 1);
        print(118, 32, ">", 1);
        drawFooter({left: "Back: done", right: "Click: params"});
    } else {
        drawCentered(32, "No presets");
        drawFooter("Back: done");
    }
    drawOverlay();

    needsRedraw = false;
}

function drawScopeOverlay() {
    if (!scopeData || scopeData.length < 256) return;
    const x0 = 0, y0 = 16, w = 128, h = 40;
    fill_rect(x0, y0, w, h, 0);
    draw_rect(x0, y0, w, h, 1);
    const innerTop = y0 + 2, innerBot = y0 + h - 2, bandH = innerBot - innerTop;
    for (let c = 0; c < 128; c++) {
        const top = scopeData.charCodeAt(c * 2) - SCOPE_ENC_BASE;
        const bot = scopeData.charCodeAt(c * 2 + 1) - SCOPE_ENC_BASE;
        if (top < 0 || bot < 0) continue;
        const yTop = innerTop + Math.round((top / (SCOPE_VAL_ROWS - 1)) * bandH);
        const yBot = innerTop + Math.round((bot / (SCOPE_VAL_ROWS - 1)) * bandH);
        draw_line(c, yTop, c, yBot, 1);
    }
    // compact param readout over the top of the waveform while dialing a knob
    if (paramHintHold > 0 && paramHintText) {
        fill_rect(x0 + 1, y0 + 1, w - 2, 9, 0);
        print(x0 + 3, y0 + 2, paramHintText, 1);
    }
}

function drawUI() {
    if (mode === "preset") {
        drawPresetUI();
        if (scopeVisible) drawScopeOverlay();
        return;
    }

    clear_screen();
    drawHeader("Ballast" + " " + pageLabel());

    drawMenuList({
        items: displayItems(),
        selectedIndex,
        listArea: { topY: LIST_TOP_Y, bottomY: FOOTER_RULE_Y },
        getLabel: (p) => p.name,
        getValue: (p, i) => {
            if (p.bank) return pageLabel();
            const paramIndex = hasEncoderBankRow() ? bankParamIndexes()[i - 1] : i;
            return paramValues[paramIndex].toFixed(PARAMS[paramIndex].dec);
        },
        valueAlignRight: true,
        editMode,
        keepOffLastRow: false,
        scrollSelectedValue: true,
        prioritizeSelectedValue: true,
        selectedMinLabelChars: 6
    });
    drawFooter(isBankRow(selectedIndex)
        ? "Click: bank"
        : (editMode ? {left: "Click: done", right: "Jog: adjust"} : "Click: edit"));
    drawOverlay();
    if (scopeVisible) drawScopeOverlay();

    needsRedraw = false;
}

function init() {
    fetchParams();
    fetchPreset();
    mode = presetCount > 0 ? "preset" : "params";
    editMode = false;
    selectedIndex = 0;
    encoderPage = 0;
    needsRedraw = true;
}

function tick() {
    if (tickOverlay()) needsRedraw = true;

    // Poll the scope. The DSP squelches silence (serves nothing when idle/quiet),
    // so a non-empty frame means the voice is sounding. Hide after a few
    // consecutive empty polls -> a brief post-release linger that is robust to
    // the chain UI's tick rate (a tick countdown would massively overshoot at a
    // slow tick rate). Inert for modules that don't serve "__scope".
    if (scopePollDiv++ % SCOPE_POLL_TICKS === 0) {
        const s = host_module_get_param("__scope");
        const next = (s === null || s === undefined) ? "" : s;
        if (next) {
            scopeEmptyPolls = 0;
            if (next !== scopeData) { scopeData = next; needsRedraw = true; }
            if (!scopeVisible) { scopeVisible = true; needsRedraw = true; hideOverlay(); }
        } else if (scopeVisible) {
            scopeEmptyPolls++;
            if (scopeEmptyPolls >= SCOPE_LINGER_POLLS) {
                scopeVisible = false;
                needsRedraw = true;
            }
        }
        if (paramHintHold > 0 && --paramHintHold === 0) needsRedraw = true;
    }

    if (needsRedraw) drawUI();
}

function onMidiMessageInternal(data) {
    const status = data[0];
    const statusType = status & 0xF0;
    const d1 = data[1];
    const d2 = data[2];

    if (statusType === MidiNoteOn || statusType === MidiNoteOff) {
        for (let k = 0; k < ENCODER_COUNT; k++) {
            if (d1 === KNOB_TOUCHES[k]) {
                const touchOn = statusType === MidiNoteOn && d2 > 0;
                const touchOff = statusType === MidiNoteOff || (statusType === MidiNoteOn && d2 === 0);
                if (touchOn) {
                    showEncoderOverlay(k, encoderParamIndex(k));
                } else if (touchOff) {
                    needsRedraw = true;
                }
                return;
            }
        }
    }

    if (statusType !== 0xB0) return;

    if (d1 === MoveMainButton && d2 > 0) {
        hideOverlay();
        if (mode === "params") toggleEditMode();
        else toggleMode();
        return;
    }

    /* Jog wheel scrolls/selects, or adjusts the selected param in edit mode. */
    if (d1 === MoveMainKnob) {
        const delta = decodeDelta(d2);
        if (mode === "preset") {
            if (delta !== 0) {
                hideOverlay();
                changePreset(delta);
            }
            return;
        }
        if (editMode) {
            const paramIndex = selectedParamIndex();
            if (delta !== 0 && paramIndex >= 0) {
                hideOverlay();
                adjustParam(paramIndex, delta);
            }
            return;
        }
        if (delta !== 0) {
            hideOverlay();
            const next = clampSelected(selectedIndex + delta);
            if (next !== selectedIndex) {
                selectIndex(next);
            }
        }
        return;
    }

    /* The 8 parameter encoders adjust the active module.json knob bank. */
    for (let k = 0; k < ENCODER_COUNT; k++) {
        if (d1 === KNOBS[k]) {
            const paramIndex = encoderParamIndex(k);
            const delta = decodeDelta(d2);
            if (delta !== 0 && paramIndex !== undefined && paramIndex < PARAMS.length) {
                if (!isBankRow(selectedIndex)) {
                    selectedIndex = displayIndexForParam(paramIndex);
                }
                editMode = false;
                adjustParam(paramIndex, delta);
                showEncoderOverlay(k, paramIndex);
            } else if (delta !== 0) {
                showEncoderOverlay(k, paramIndex);
            }
            return;
        }
    }
}

globalThis.chain_ui = {
    init,
    tick,
    onMidiMessageInternal
};
