/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of filter_params.gen.inc so the param count and enum are
 * visible to filter_core.h, which needs FILTER_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking filter_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef FILTER_PARAMS_GEN_H
#define FILTER_PARAMS_GEN_H

#define FILTER_PARAM_COUNT 3

enum {
    FILTER_PARAM_CUTOFF = 0,
    FILTER_PARAM_RESONANCE = 1,
    FILTER_PARAM_MORPH = 2
};

#endif
