/* GENERATED by scripts/gen-faust.ts from filter.dsp via Faust */
/* Regenerate with: mise run gen-faust (or: pnpm run gen-faust) */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"

/* ------------------------------------------------------------
name: "filter"
Code generated with Faust 2.85.5 (https://faust.grame.fr)
Compilation options: -a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn filter_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */

#ifndef  __filter_faust_H__
#define  __filter_faust_H__

/* Faust architecture file: library-only output.
 *
 * Used by scripts/gen-faust.ts to generate the per-module C from a .dsp
 * source. Produces only the DSP class definitions (struct + functions like
 * `new<prefix>`, `init<prefix>`, `compute<prefix>`, `buildUserInterface<prefix>`)
 * with no `main()`. The moveforge per-module adapter
 * (`<id>_core.c`) consumes that output.
 *
 * Faust replaces <<includeIntrinsic>> and <<includeclass>> at codegen time.
 * Keep this file small and dependency-light so the generated artifact stays
 * portable and drops cleanly into the existing Schwung wrapper pipeline.
 */

#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif

/* The generated `buildUserInterface` walks a UIGlue struct of callbacks.
 * We don't use Faust's UI to discover params at runtime — the moveforge
 * adapter knows param indices statically — so we provide a stub type
 * that satisfies the symbol without pulling in Faust's UI runtime. */
typedef struct UIGlue UIGlue;
typedef struct MetaGlue MetaGlue;


#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 


#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

/* link with : "" */
#include <math.h>
#include <stdint.h>
#include <stdlib.h>

static float filter_faust_faustpower2_f(float value) {
	return value * value;
}

#ifndef FAUSTCLASS 
#define FAUSTCLASS filter_faust
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif
#ifndef FAUSTMAXI
#define FAUSTMAXI
inline int faustmaxi(int a, int b) { return (a > b) ? a : b; }
inline int faustmini(int a, int b) { return (a < b) ? a : b; }
#endif

typedef struct {
	FAUSTFLOAT fHslider0;
	int fSampleRate;
	float fConst0;
	float fConst1;
	FAUSTFLOAT fHslider1;
	float fRec0[2];
	float fRec1[2];
	float fConst2;
	FAUSTFLOAT fHslider2;
	float fConst3;
	float fRec4[2];
	float fRec5[2];
	float fRec6[2];
} filter_faust;

filter_faust* newfilter_faust() { 
	filter_faust* dsp = (filter_faust*)calloc(1, sizeof(filter_faust));
	return dsp;
}

void deletefilter_faust(filter_faust* dsp) { 
	free(dsp);
}

void metadatafilter_faust(MetaGlue* m) { 
	m->declare(m->metaInterface, "compile_options", "-a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn filter_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
	m->declare(m->metaInterface, "filename", "filter.dsp");
	m->declare(m->metaInterface, "filters.lib/lowpass0_highpass1", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/name", "Faust Filters Library");
	m->declare(m->metaInterface, "filters.lib/svf:author", "Oleg Nesterov");
	m->declare(m->metaInterface, "filters.lib/svf:copyright", "Copyright (C) 2020 Oleg Nesterov <oleg@redhat.com>");
	m->declare(m->metaInterface, "filters.lib/svf:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/svf_morph:author", "David Braun and Clarence W. Rowley");
	m->declare(m->metaInterface, "filters.lib/svf_morph:copyright", "Copyright (C) 2024 David Braun <braun@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/svf_morph:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/version", "1.7.1");
	m->declare(m->metaInterface, "maths.lib/author", "GRAME");
	m->declare(m->metaInterface, "maths.lib/copyright", "GRAME");
	m->declare(m->metaInterface, "maths.lib/license", "LGPL with exception");
	m->declare(m->metaInterface, "maths.lib/name", "Faust Math Library");
	m->declare(m->metaInterface, "maths.lib/version", "2.9.0");
	m->declare(m->metaInterface, "name", "filter");
	m->declare(m->metaInterface, "platform.lib/name", "Generic Platform Library");
	m->declare(m->metaInterface, "platform.lib/version", "1.3.0");
	m->declare(m->metaInterface, "routes.lib/name", "Faust Signal Routing Library");
	m->declare(m->metaInterface, "routes.lib/version", "1.3.0");
	m->declare(m->metaInterface, "signals.lib/name", "Faust Routing Library");
	m->declare(m->metaInterface, "signals.lib/version", "1.6.0");
}

int getSampleRatefilter_faust(filter_faust* RESTRICT dsp) {
	return dsp->fSampleRate;
}

int getNumInputsfilter_faust(filter_faust* RESTRICT dsp) {
	return 2;
}
int getNumOutputsfilter_faust(filter_faust* RESTRICT dsp) {
	return 2;
}

void classInitfilter_faust(int sample_rate) {
}

void instanceResetUserInterfacefilter_faust(filter_faust* dsp) {
	dsp->fHslider0 = (FAUSTFLOAT)(0.0f);
	dsp->fHslider1 = (FAUSTFLOAT)(1.0f);
	dsp->fHslider2 = (FAUSTFLOAT)(0.0f);
}

void instanceClearfilter_faust(filter_faust* dsp) {
	/* C99 loop */
	{
		int l0;
		for (l0 = 0; l0 < 2; l0 = l0 + 1) {
			dsp->fRec0[l0] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l1;
		for (l1 = 0; l1 < 2; l1 = l1 + 1) {
			dsp->fRec1[l1] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l2;
		for (l2 = 0; l2 < 2; l2 = l2 + 1) {
			dsp->fRec4[l2] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l3;
		for (l3 = 0; l3 < 2; l3 = l3 + 1) {
			dsp->fRec5[l3] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l4;
		for (l4 = 0; l4 < 2; l4 = l4 + 1) {
			dsp->fRec6[l4] = 0.0f;
		}
	}
}

void instanceConstantsfilter_faust(filter_faust* dsp, int sample_rate) {
	dsp->fSampleRate = sample_rate;
	dsp->fConst0 = fminf(1.92e+05f, fmaxf(1.0f, (float)(dsp->fSampleRate)));
	dsp->fConst1 = 62.831852f / dsp->fConst0;
	dsp->fConst2 = 88.2f / dsp->fConst0;
	dsp->fConst3 = 1.0f - 44.1f / dsp->fConst0;
}
	
void instanceInitfilter_faust(filter_faust* dsp, int sample_rate) {
	instanceConstantsfilter_faust(dsp, sample_rate);
	instanceResetUserInterfacefilter_faust(dsp);
	instanceClearfilter_faust(dsp);
}

void initfilter_faust(filter_faust* dsp, int sample_rate) {
	classInitfilter_faust(sample_rate);
	instanceInitfilter_faust(dsp, sample_rate);
}

void buildUserInterfacefilter_faust(filter_faust* dsp, UIGlue* ui_interface) {
	ui_interface->openVerticalBox(ui_interface->uiInterface, "filter");
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "cutoff", &dsp->fHslider1, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "morph", &dsp->fHslider2, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "resonance", &dsp->fHslider0, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->closeBox(ui_interface->uiInterface);
}

void computefilter_faust(filter_faust* dsp, int count, FAUSTFLOAT** RESTRICT inputs, FAUSTFLOAT** RESTRICT outputs) {
	FAUSTFLOAT* input0 = inputs[0];
	FAUSTFLOAT* input1 = inputs[1];
	FAUSTFLOAT* output0 = outputs[0];
	FAUSTFLOAT* output1 = outputs[1];
	float fSlow0 = powf(4e+01f, (float)(dsp->fHslider0));
	float fSlow1 = 1.0f / sqrtf(fSlow0);
	float fSlow2 = tanf(dsp->fConst1 * powf(9e+02f, (float)(dsp->fHslider1)));
	float fSlow3 = 2.0f / fSlow0;
	float fSlow4 = fSlow2 * (fSlow2 + fSlow3) + 1.0f;
	float fSlow5 = 2.0f / fSlow4;
	float fSlow6 = fSlow2 / fSlow4;
	float fSlow7 = 1.0f / fSlow4;
	float fSlow8 = dsp->fConst2 * (float)(dsp->fHslider2);
	/* C99 loop */
	{
		int i0;
		for (i0 = 0; i0 < count; i0 = i0 + 1) {
			float fTemp0 = (float)(input0[i0]);
			float fTemp1 = dsp->fRec0[1] + fSlow2 * (fTemp0 - dsp->fRec1[1]);
			float fTemp2 = fSlow5 * fTemp1 - dsp->fRec0[1];
			dsp->fRec0[0] = ((fabsf(fTemp2) > 1.1754944e-38f) ? fTemp2 : 0.0f);
			float fTemp3 = dsp->fRec1[1] + fSlow6 * fTemp1;
			float fTemp4 = 2.0f * fTemp3 - dsp->fRec1[1];
			dsp->fRec1[0] = ((fabsf(fTemp4) > 1.1754944e-38f) ? fTemp4 : 0.0f);
			float fTemp5 = fSlow7 * fTemp1;
			float fRec2 = ((fabsf(fTemp5) > 1.1754944e-38f) ? fTemp5 : 0.0f);
			float fRec3 = ((fabsf(fTemp3) > 1.1754944e-38f) ? fTemp3 : 0.0f);
			float fTemp6 = fSlow8 + dsp->fConst3 * dsp->fRec4[1];
			dsp->fRec4[0] = ((fabsf(fTemp6) > 1.1754944e-38f) ? fTemp6 : 0.0f);
			float fTemp7 = dsp->fRec4[0] + -1.0f;
			float fTemp8 = fmaxf(-fTemp7, 0.0f);
			float fTemp9 = sqrtf(1.0f - filter_faust_faustpower2_f(fTemp7));
			float fTemp10 = fmaxf(fTemp7, 0.0f);
			output0[i0] = (FAUSTFLOAT)(tanhf(fSlow1 * (fRec3 * fTemp8 + fRec2 * fTemp9 + (fTemp0 - (fRec3 + fSlow3 * fRec2)) * fTemp10)));
			float fTemp11 = (float)(input1[i0]);
			float fTemp12 = dsp->fRec5[1] + fSlow2 * (fTemp11 - dsp->fRec6[1]);
			float fTemp13 = fSlow5 * fTemp12 - dsp->fRec5[1];
			dsp->fRec5[0] = ((fabsf(fTemp13) > 1.1754944e-38f) ? fTemp13 : 0.0f);
			float fTemp14 = dsp->fRec6[1] + fSlow6 * fTemp12;
			float fTemp15 = 2.0f * fTemp14 - dsp->fRec6[1];
			dsp->fRec6[0] = ((fabsf(fTemp15) > 1.1754944e-38f) ? fTemp15 : 0.0f);
			float fTemp16 = fSlow7 * fTemp12;
			float fRec7 = ((fabsf(fTemp16) > 1.1754944e-38f) ? fTemp16 : 0.0f);
			float fRec8 = ((fabsf(fTemp14) > 1.1754944e-38f) ? fTemp14 : 0.0f);
			output1[i0] = (FAUSTFLOAT)(tanhf(fSlow1 * (fRec8 * fTemp8 + fRec7 * fTemp9 + fTemp10 * (fTemp11 - (fRec8 + fSlow3 * fRec7)))));
			dsp->fRec0[1] = dsp->fRec0[0];
			dsp->fRec1[1] = dsp->fRec1[0];
			dsp->fRec4[1] = dsp->fRec4[0];
			dsp->fRec5[1] = dsp->fRec5[0];
			dsp->fRec6[1] = dsp->fRec6[0];
		}
	}
}

#ifdef __cplusplus
}
#endif

#endif

#pragma GCC diagnostic pop
