/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of filter_params.gen.inc so the param count and enum are
 * visible to filter_core.h, which needs FILTER_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking filter_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef FILTER_PARAMS_GEN_H
#define FILTER_PARAMS_GEN_H

#define FILTER_PARAM_COUNT 8

enum {
    FILTER_PARAM_CUTOFF = 0,
    FILTER_PARAM_RESONANCE = 1,
    FILTER_PARAM_MORPH = 2,
    FILTER_PARAM_ENV_AMOUNT = 3,
    FILTER_PARAM_FILTER_ATTACK = 4,
    FILTER_PARAM_FILTER_DECAY = 5,
    FILTER_PARAM_FILTER_SUSTAIN = 6,
    FILTER_PARAM_FILTER_RELEASE = 7
};

#endif
