/*
 * Dustline Chain UI — GENERATED by scripts/gen-ui-chain.ts from module.json.
 * Do not edit by hand: change module.json and re-run `mise run gen-ui-chain`.
 *
 * Scrollable parameter editor shown when this module is opened (wheel press)
 * in a chain slot. Top knobs (Knob 1..5) adjust the visible params; the
 * jog wheel scrolls when there are more than 5. Sets globalThis.chain_ui.
 */

import {
    MoveMainButton, MoveMainKnob,
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4, MoveKnob5, MoveKnob6
} from '/data/UserData/schwung/shared/constants.mjs';

import { decodeDelta } from '/data/UserData/schwung/shared/input_filter.mjs';

import { drawMenuHeader as drawHeader } from '/data/UserData/schwung/shared/menu_layout.mjs';

const SCREEN_WIDTH = 128;
const KNOBS = [MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4, MoveKnob5, MoveKnob6];

const PARAMS = [
    { key: "volume", name: "Volume", min: 0, max: 1, step: 0.01, dec: 2, def: 0.72 },
    { key: "wave", name: "Wave", min: 0, max: 1, step: 0.01, dec: 2, def: 0.35 },
    { key: "noise", name: "Noise", min: 0, max: 1, step: 0.01, dec: 2, def: 0.18 },
    { key: "cutoff", name: "Cutoff", min: 0, max: 1, step: 0.01, dec: 2, def: 0.42 },
    { key: "resonance", name: "Reso", min: 0, max: 0.95, step: 0.01, dec: 2, def: 0.18 },
    { key: "attack", name: "Attack", min: 0.001, max: 2, step: 0.03998, dec: 2, def: 0.008 },
    { key: "release", name: "Release", min: 0.02, max: 6, step: 0.1196, dec: 1, def: 0.55 },
    { key: "drive", name: "Drive", min: 0, max: 1, step: 0.01, dec: 2, def: 0.22 },
    { key: "bend_range", name: "Bend", min: 0, max: 12, step: 0.24, dec: 1, def: 2 }
];

const VISIBLE = Math.min(PARAMS.length, 5);
const LIST_Y = 14;
const LINE_H = 8;
const MAX_SCROLL = Math.max(0, PARAMS.length - VISIBLE);

let scrollTop = 0;
let selectedIndex = 0;
let paramValues = PARAMS.map((p) => p.def);
let presetCount = 0;
let presetIndex = 0;
let presetName = "";
let mode = "params";
let editMode = false;
let needsRedraw = true;

function clampScroll(v) {
    return Math.max(0, Math.min(MAX_SCROLL, v));
}

function clampSelected(v) {
    return Math.max(0, Math.min(Math.max(0, PARAMS.length - 1), v));
}

function ensureSelectedVisible() {
    if (selectedIndex < scrollTop) scrollTop = selectedIndex;
    if (selectedIndex >= scrollTop + VISIBLE) scrollTop = selectedIndex - VISIBLE + 1;
    scrollTop = clampScroll(scrollTop);
}

function fetchParams() {
    for (let i = 0; i < PARAMS.length; i++) {
        const val = host_module_get_param(PARAMS[i].key);
        if (val !== null && val !== undefined) {
            const f = parseFloat(val);
            if (!isNaN(f)) paramValues[i] = f;
        }
    }
}

function fetchPreset() {
    const count = host_module_get_param("preset_count");
    const parsedCount = count !== null && count !== undefined ? parseInt(count) : 0;
    presetCount = isNaN(parsedCount) ? 0 : Math.max(0, parsedCount);

    const preset = host_module_get_param("preset");
    const parsedPreset = preset !== null && preset !== undefined ? parseInt(preset) : 0;
    presetIndex = isNaN(parsedPreset) ? 0 : Math.max(0, Math.min(Math.max(0, presetCount - 1), parsedPreset));

    presetName = host_module_get_param("preset_name") || "";
}

function setParam(index, value) {
    const param = PARAMS[index];
    value = Math.max(param.min, Math.min(param.max, value));
    paramValues[index] = value;
    host_module_set_param(param.key, value.toFixed(2));
}

function adjustParam(index, delta) {
    setParam(index, paramValues[index] + delta * PARAMS[index].step);
    needsRedraw = true;
}

function changePreset(delta) {
    if (presetCount <= 0) return;
    let next = presetIndex + delta;
    if (next < 0) next = presetCount - 1;
    if (next >= presetCount) next = 0;
    presetIndex = next;
    host_module_set_param("preset", String(presetIndex));
    fetchPreset();
    fetchParams();
    needsRedraw = true;
}

function toggleMode() {
    if (presetCount <= 0) return;
    mode = mode === "preset" ? "params" : "preset";
    editMode = false;
    needsRedraw = true;
}

function toggleEditMode() {
    if (mode !== "params" || PARAMS.length === 0) return;
    editMode = !editMode;
    ensureSelectedVisible();
    needsRedraw = true;
}

function drawCentered(y, text) {
    const s = String(text || "");
    const x = Math.max(0, Math.floor((SCREEN_WIDTH - s.length * 5) / 2));
    print(x, y, s, 1);
}

function drawPresetUI() {
    clear_screen();
    drawHeader("Dustline");

    fetchPreset();
    if (presetCount > 0) {
        drawCentered(24, String(presetIndex + 1) + " / " + String(presetCount));
        drawCentered(36, presetName || "Preset " + String(presetIndex + 1));
        print(4, 32, "<", 1);
        print(SCREEN_WIDTH - 10, 32, ">", 1);
        print(2, 56, "Click: params", 1);
    } else {
        drawCentered(32, "No presets");
    }

    needsRedraw = false;
}

function drawUI() {
    if (mode === "preset") {
        drawPresetUI();
        return;
    }

    clear_screen();
    drawHeader("Dustline");

    const end = Math.min(scrollTop + VISIBLE, PARAMS.length);
    for (let i = scrollTop; i < end; i++) {
        const y = LIST_Y + (i - scrollTop) * LINE_H;
        const param = PARAMS[i];
        const marker = i === selectedIndex ? (editMode ? "*" : ">") : " ";
        print(2, y, marker + param.name, 1);
        const valueStr = paramValues[i].toFixed(param.dec);
        print(SCREEN_WIDTH - valueStr.length * 6 - 8, y, valueStr, 1);
    }

    /* Scroll indicators when the list overflows the screen. */
    if (scrollTop > 0) print(SCREEN_WIDTH - 6, LIST_Y, "^", 1);
    if (end < PARAMS.length) print(SCREEN_WIDTH - 6, LIST_Y + (VISIBLE - 1) * LINE_H, "v", 1);
    print(2, 56, editMode ? "Click: done" : "Click: edit", 1);

    needsRedraw = false;
}

function init() {
    fetchParams();
    fetchPreset();
    mode = presetCount > 0 ? "preset" : "params";
    editMode = false;
    scrollTop = 0;
    selectedIndex = 0;
    needsRedraw = true;
}

function tick() {
    if (needsRedraw) drawUI();
}

function onMidiMessageInternal(data) {
    const status = data[0];
    const d1 = data[1];
    const d2 = data[2];
    if ((status & 0xF0) !== 0xB0) return;

    if (d1 === MoveMainButton && d2 > 0) {
        if (mode === "params") toggleEditMode();
        else toggleMode();
        return;
    }

    /* Jog wheel scrolls the visible window. */
    if (d1 === MoveMainKnob) {
        const delta = decodeDelta(d2);
        if (mode === "preset") {
            if (delta !== 0) changePreset(delta);
            return;
        }
        if (editMode) {
            if (delta !== 0) adjustParam(selectedIndex, delta);
            return;
        }
        if (delta !== 0) {
            const next = clampSelected(selectedIndex + delta);
            if (next !== selectedIndex) {
                selectedIndex = next;
                ensureSelectedVisible();
                needsRedraw = true;
            }
        }
        return;
    }

    /* Each visible row is adjusted by its corresponding top knob. */
    for (let k = 0; k < VISIBLE; k++) {
        if (d1 === KNOBS[k]) {
            const delta = decodeDelta(d2);
            if (delta !== 0) adjustParam(scrollTop + k, delta);
            return;
        }
    }
}

globalThis.chain_ui = {
    init,
    tick,
    onMidiMessageInternal
};
