#ifndef TRAIL_CORE_H
#define TRAIL_CORE_H

/* Public moveforge core API for the Faust-backed Trail delay module.
 *
 * The underlying DSP is generated by Faust from trail.dsp into
 * trail_faust.c. This header exposes a thin C adapter so the rest of the
 * moveforge pipeline (wrapper, host renderers, tests) treats the module
 * identically to a hand-written C module.
 *
 * Unlike a 1:1 Faust module, two moveforge params (time, sync) have no
 * matching Faust hslider — instead the adapter combines them with the
 * host tempo to compute the delay length in samples and writes it to an
 * internal Faust control slider ("_dtime"). All other params map 1:1. */

/* Max fractional-delay length, in samples. Power of two (2^17 ~= 2.97 s at
 * 44.1 kHz) so it covers free time (up to ~2 s) and synced divisions up to a
 * 1/1 bar at typical techno tempos. MUST match MAXDELAY in trail.dsp. */
#define TRAIL_MAXDELAY 131072

/* Number of moveforge params (must match module.json param count). */
#define TRAIL_NUM_PARAMS 9

typedef struct {
    /* moveforge params (one float field per module.json key). */
    float time;
    float sync;
    float feedback;
    float tone;
    float mod;
    float width;
    float drive;
    float space;
    float mix;

    /* Current host tempo, updated by trail_set_tempo. Defaults to 120. */
    float bpm;
    int clock_running;

    /* Opaque pointer to the Faust-generated DSP instance (trail_faust*).
     * Allocated by trail_init via newtrail_faust(), freed by trail_destroy. */
    void *fdsp;

    /* Captured zone addresses (FAUSTFLOAT*) for each moveforge param id,
     * populated by buildUserInterface during init. Indexed by
     * TRAIL_PARAM_* enum values. NULL for params with no Faust slider
     * (time, sync). */
    void *zones[TRAIL_NUM_PARAMS];

    /* Captured zone for the internal "_dtime" slider (delay length in
     * samples), driven by the adapter from time/sync/bpm each block. */
    void *dtime_zone;
} trail_core_t;

void trail_init(trail_core_t *s);
void trail_destroy(trail_core_t *s);
void trail_apply_defaults(trail_core_t *s);
int trail_param_id(const char *key);
void trail_set_param(trail_core_t *s, int param_id, float value);
float trail_get_param(const trail_core_t *s, int param_id);

/* Update the host tempo used when sync != Free. bpm <= 0 falls back to 120. */
void trail_set_tempo(trail_core_t *s, float bpm, int clock_running);

void trail_process_float(trail_core_t *s,
                         const float *in_left, const float *in_right,
                         float *out_left, float *out_right,
                         int frames);

#endif
