/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of trail_params.gen.inc so the param count and enum are
 * visible to trail_core.h, which needs TRAIL_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking trail_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef TRAIL_PARAMS_GEN_H
#define TRAIL_PARAMS_GEN_H

#define TRAIL_PARAM_COUNT 9

enum {
    TRAIL_PARAM_TIME = 0,
    TRAIL_PARAM_SYNC = 1,
    TRAIL_PARAM_FEEDBACK = 2,
    TRAIL_PARAM_TONE = 3,
    TRAIL_PARAM_MOD = 4,
    TRAIL_PARAM_WIDTH = 5,
    TRAIL_PARAM_DRIVE = 6,
    TRAIL_PARAM_SPACE = 7,
    TRAIL_PARAM_MIX = 8
};

#endif
