/* GENERATED by scripts/gen-faust.ts from trail.dsp via Faust */
/* Regenerate with: mise run gen-faust (or: pnpm run gen-faust) */

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"

/* ------------------------------------------------------------
name: "trail"
Code generated with Faust 2.85.5 (https://faust.grame.fr)
Compilation options: -a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn trail_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1
------------------------------------------------------------ */

#ifndef  __trail_faust_H__
#define  __trail_faust_H__

/* Faust architecture file: library-only output.
 *
 * Used by scripts/gen-faust.ts to generate the per-module C from a .dsp
 * source. Produces only the DSP class definitions (struct + functions like
 * `new<prefix>`, `init<prefix>`, `compute<prefix>`, `buildUserInterface<prefix>`)
 * with no `main()`. The moveforge per-module adapter
 * (`<id>_core.c`) consumes that output.
 *
 * Faust replaces <<includeIntrinsic>> and <<includeclass>> at codegen time.
 * Keep this file small and dependency-light so the generated artifact stays
 * portable and drops cleanly into the existing Schwung wrapper pipeline.
 */

#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif

/* The generated `buildUserInterface` walks a UIGlue struct of callbacks.
 * We don't use Faust's UI to discover params at runtime — the moveforge
 * adapter knows param indices statically — so we provide a stub type
 * that satisfies the symbol without pulling in Faust's UI runtime. */
typedef struct UIGlue UIGlue;
typedef struct MetaGlue MetaGlue;


#ifndef FAUSTFLOAT
#define FAUSTFLOAT float
#endif 


#ifdef __cplusplus
extern "C" {
#endif

#if defined(_WIN32)
#define RESTRICT __restrict
#else
#define RESTRICT __restrict__
#endif

/* link with : "" */
#include <math.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct {
	int iVec2[2];
	int iRec4[2];
	int fSampleRate;
} trail_faustSIG0;

static trail_faustSIG0* newtrail_faustSIG0() { return (trail_faustSIG0*)calloc(1, sizeof(trail_faustSIG0)); }
static void deletetrail_faustSIG0(trail_faustSIG0* dsp) { free(dsp); }

int getNumInputstrail_faustSIG0(trail_faustSIG0* RESTRICT dsp) {
	return 0;
}
int getNumOutputstrail_faustSIG0(trail_faustSIG0* RESTRICT dsp) {
	return 1;
}

static void instanceInittrail_faustSIG0(trail_faustSIG0* dsp, int sample_rate) {
	dsp->fSampleRate = sample_rate;
	/* C99 loop */
	{
		int l4;
		for (l4 = 0; l4 < 2; l4 = l4 + 1) {
			dsp->iVec2[l4] = 0;
		}
	}
	/* C99 loop */
	{
		int l5;
		for (l5 = 0; l5 < 2; l5 = l5 + 1) {
			dsp->iRec4[l5] = 0;
		}
	}
}

static void filltrail_faustSIG0(trail_faustSIG0* dsp, int count, float* table) {
	/* C99 loop */
	{
		int i1;
		for (i1 = 0; i1 < count; i1 = i1 + 1) {
			dsp->iVec2[0] = 1;
			dsp->iRec4[0] = (dsp->iVec2[1] + dsp->iRec4[1]) % 65536;
			table[i1] = sinf(9.58738e-05f * (float)(dsp->iRec4[0]));
			dsp->iVec2[1] = dsp->iVec2[0];
			dsp->iRec4[1] = dsp->iRec4[0];
		}
	}
}

static float ftbl0trail_faustSIG0[65536];
static float trail_faust_faustpower2_f(float value) {
	return value * value;
}

#ifndef FAUSTCLASS 
#define FAUSTCLASS trail_faust
#endif

#ifdef __APPLE__ 
#define exp10f __exp10f
#define exp10 __exp10
#endif
#ifndef FAUSTMAXI
#define FAUSTMAXI
inline int faustmaxi(int a, int b) { return (a > b) ? a : b; }
inline int faustmini(int a, int b) { return (a < b) ? a : b; }
#endif

typedef struct {
	float fVec0[2];
	FAUSTFLOAT fHslider0;
	int fSampleRate;
	float fConst0;
	float fConst1;
	int iVec1[2];
	float fRec0[2];
	FAUSTFLOAT fHslider1;
	float fConst2;
	FAUSTFLOAT fHslider2;
	float fRec3[2];
	float fConst3;
	float fRec5[2];
	FAUSTFLOAT fHslider3;
	float fRec6[2];
	FAUSTFLOAT fHslider4;
	float fRec7[2];
	float fConst4;
	FAUSTFLOAT fHslider5;
	float fConst5;
	float fRec9[2];
	float fRec11[2];
	float fRec12[2];
	float fRec13[2];
	float fRec10[2];
	float fRec14[2];
	float fRec8[2];
	FAUSTFLOAT fHslider6;
	float fRec15[2];
	float fRec17[2];
	float fRec16[2];
	int IOTA0;
	float fVec3[262144];
	float fRec1[3];
	float fConst6;
	float fRec18[2];
	float fVec4[262144];
	float fRec2[3];
	FAUSTFLOAT fHslider7;
	float fRec19[2];
	float fRec29[2];
	float fVec5[8192];
	int iConst7;
	int iConst8;
	float fRec28[2];
	float fRec31[2];
	float fVec6[8192];
	int iConst9;
	int iConst10;
	float fRec30[2];
	float fRec33[2];
	float fVec7[8192];
	int iConst11;
	int iConst12;
	float fRec32[2];
	float fRec35[2];
	float fVec8[8192];
	int iConst13;
	int iConst14;
	float fRec34[2];
	float fRec37[2];
	float fVec9[8192];
	int iConst15;
	int iConst16;
	float fRec36[2];
	float fRec39[2];
	float fVec10[8192];
	int iConst17;
	int iConst18;
	float fRec38[2];
	float fRec41[2];
	float fVec11[8192];
	int iConst19;
	int iConst20;
	float fRec40[2];
	float fRec43[2];
	float fVec12[8192];
	int iConst21;
	int iConst22;
	float fRec42[2];
	float fVec13[2048];
	int iConst23;
	int iConst24;
	float fRec26[2];
	float fVec14[2048];
	int iConst25;
	int iConst26;
	float fRec24[2];
	float fVec15[2048];
	int iConst27;
	int iConst28;
	float fRec22[2];
	float fVec16[1024];
	int iConst29;
	int iConst30;
	float fRec20[2];
	float fRec53[2];
	float fVec17[8192];
	int iConst31;
	float fRec52[2];
	float fRec55[2];
	float fVec18[8192];
	int iConst32;
	float fRec54[2];
	float fRec57[2];
	float fVec19[8192];
	int iConst33;
	float fRec56[2];
	float fRec59[2];
	float fVec20[8192];
	int iConst34;
	float fRec58[2];
	float fRec61[2];
	float fVec21[8192];
	int iConst35;
	float fRec60[2];
	float fRec63[2];
	float fVec22[8192];
	int iConst36;
	float fRec62[2];
	float fRec65[2];
	float fVec23[8192];
	int iConst37;
	float fRec64[2];
	float fRec67[2];
	float fVec24[8192];
	int iConst38;
	float fRec66[2];
	float fVec25[2048];
	int iConst39;
	float fRec50[2];
	float fVec26[2048];
	int iConst40;
	float fRec48[2];
	float fVec27[2048];
	int iConst41;
	float fRec46[2];
	float fVec28[1024];
	int iConst42;
	float fRec44[2];
} trail_faust;

trail_faust* newtrail_faust() { 
	trail_faust* dsp = (trail_faust*)calloc(1, sizeof(trail_faust));
	return dsp;
}

void deletetrail_faust(trail_faust* dsp) { 
	free(dsp);
}

void metadatatrail_faust(MetaGlue* m) { 
	m->declare(m->metaInterface, "basics.lib/name", "Faust Basic Element Library");
	m->declare(m->metaInterface, "basics.lib/version", "1.22.0");
	m->declare(m->metaInterface, "compile_options", "-a src/host/faust_module_arch.c.in -lang c -fpga-mem-th 4 -ct 1 -cn trail_faust -es 1 -mcd 16 -mdd 1024 -mdy 33 -single -ftz 1");
	m->declare(m->metaInterface, "delays.lib/fdelay4:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "delays.lib/fdelayltv:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "delays.lib/name", "Faust Delay Library");
	m->declare(m->metaInterface, "delays.lib/version", "1.2.0");
	m->declare(m->metaInterface, "filename", "trail.dsp");
	m->declare(m->metaInterface, "filters.lib/allpass_comb:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/allpass_comb:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/allpass_comb:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/lowpass0_highpass1", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/name", "Faust Filters Library");
	m->declare(m->metaInterface, "filters.lib/tf1:author", "Julius O. Smith III");
	m->declare(m->metaInterface, "filters.lib/tf1:copyright", "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>");
	m->declare(m->metaInterface, "filters.lib/tf1:license", "MIT-style STK-4.3 license");
	m->declare(m->metaInterface, "filters.lib/version", "1.7.1");
	m->declare(m->metaInterface, "maths.lib/author", "GRAME");
	m->declare(m->metaInterface, "maths.lib/copyright", "GRAME");
	m->declare(m->metaInterface, "maths.lib/license", "LGPL with exception");
	m->declare(m->metaInterface, "maths.lib/name", "Faust Math Library");
	m->declare(m->metaInterface, "maths.lib/version", "2.9.0");
	m->declare(m->metaInterface, "moveforge.lib/author", "moveforge");
	m->declare(m->metaInterface, "moveforge.lib/name", "moveforge");
	m->declare(m->metaInterface, "name", "trail");
	m->declare(m->metaInterface, "oscillators.lib/name", "Faust Oscillator Library");
	m->declare(m->metaInterface, "oscillators.lib/version", "1.7.0");
	m->declare(m->metaInterface, "platform.lib/name", "Generic Platform Library");
	m->declare(m->metaInterface, "platform.lib/version", "1.3.0");
	m->declare(m->metaInterface, "reverbs.lib/mono_freeverb:author", "Romain Michon");
	m->declare(m->metaInterface, "reverbs.lib/name", "Faust Reverb Library");
	m->declare(m->metaInterface, "reverbs.lib/stereo_freeverb:author", "Romain Michon");
	m->declare(m->metaInterface, "reverbs.lib/version", "1.5.1");
	m->declare(m->metaInterface, "signals.lib/name", "Faust Routing Library");
	m->declare(m->metaInterface, "signals.lib/version", "1.6.0");
}

int getSampleRatetrail_faust(trail_faust* RESTRICT dsp) {
	return dsp->fSampleRate;
}

int getNumInputstrail_faust(trail_faust* RESTRICT dsp) {
	return 2;
}
int getNumOutputstrail_faust(trail_faust* RESTRICT dsp) {
	return 2;
}

void classInittrail_faust(int sample_rate) {
	trail_faustSIG0* sig0 = newtrail_faustSIG0();
	instanceInittrail_faustSIG0(sig0, sample_rate);
	filltrail_faustSIG0(sig0, 65536, ftbl0trail_faustSIG0);
	deletetrail_faustSIG0(sig0);
}

void instanceResetUserInterfacetrail_faust(trail_faust* dsp) {
	dsp->fHslider0 = (FAUSTFLOAT)(0.18f);
	dsp->fHslider1 = (FAUSTFLOAT)(1.323e+04f);
	dsp->fHslider2 = (FAUSTFLOAT)(0.12f);
	dsp->fHslider3 = (FAUSTFLOAT)(0.22f);
	dsp->fHslider4 = (FAUSTFLOAT)(0.5f);
	dsp->fHslider5 = (FAUSTFLOAT)(0.55f);
	dsp->fHslider6 = (FAUSTFLOAT)(0.12f);
	dsp->fHslider7 = (FAUSTFLOAT)(0.05f);
}

void instanceCleartrail_faust(trail_faust* dsp) {
	/* C99 loop */
	{
		int l0;
		for (l0 = 0; l0 < 2; l0 = l0 + 1) {
			dsp->fVec0[l0] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l1;
		for (l1 = 0; l1 < 2; l1 = l1 + 1) {
			dsp->iVec1[l1] = 0;
		}
	}
	/* C99 loop */
	{
		int l2;
		for (l2 = 0; l2 < 2; l2 = l2 + 1) {
			dsp->fRec0[l2] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l3;
		for (l3 = 0; l3 < 2; l3 = l3 + 1) {
			dsp->fRec3[l3] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l6;
		for (l6 = 0; l6 < 2; l6 = l6 + 1) {
			dsp->fRec5[l6] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l7;
		for (l7 = 0; l7 < 2; l7 = l7 + 1) {
			dsp->fRec6[l7] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l8;
		for (l8 = 0; l8 < 2; l8 = l8 + 1) {
			dsp->fRec7[l8] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l9;
		for (l9 = 0; l9 < 2; l9 = l9 + 1) {
			dsp->fRec9[l9] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l10;
		for (l10 = 0; l10 < 2; l10 = l10 + 1) {
			dsp->fRec11[l10] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l11;
		for (l11 = 0; l11 < 2; l11 = l11 + 1) {
			dsp->fRec12[l11] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l12;
		for (l12 = 0; l12 < 2; l12 = l12 + 1) {
			dsp->fRec13[l12] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l13;
		for (l13 = 0; l13 < 2; l13 = l13 + 1) {
			dsp->fRec10[l13] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l14;
		for (l14 = 0; l14 < 2; l14 = l14 + 1) {
			dsp->fRec14[l14] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l15;
		for (l15 = 0; l15 < 2; l15 = l15 + 1) {
			dsp->fRec8[l15] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l16;
		for (l16 = 0; l16 < 2; l16 = l16 + 1) {
			dsp->fRec15[l16] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l17;
		for (l17 = 0; l17 < 2; l17 = l17 + 1) {
			dsp->fRec17[l17] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l18;
		for (l18 = 0; l18 < 2; l18 = l18 + 1) {
			dsp->fRec16[l18] = 0.0f;
		}
	}
	dsp->IOTA0 = 0;
	/* C99 loop */
	{
		int l19;
		for (l19 = 0; l19 < 262144; l19 = l19 + 1) {
			dsp->fVec3[l19] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l20;
		for (l20 = 0; l20 < 3; l20 = l20 + 1) {
			dsp->fRec1[l20] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l21;
		for (l21 = 0; l21 < 2; l21 = l21 + 1) {
			dsp->fRec18[l21] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l22;
		for (l22 = 0; l22 < 262144; l22 = l22 + 1) {
			dsp->fVec4[l22] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l23;
		for (l23 = 0; l23 < 3; l23 = l23 + 1) {
			dsp->fRec2[l23] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l24;
		for (l24 = 0; l24 < 2; l24 = l24 + 1) {
			dsp->fRec19[l24] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l25;
		for (l25 = 0; l25 < 2; l25 = l25 + 1) {
			dsp->fRec29[l25] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l26;
		for (l26 = 0; l26 < 8192; l26 = l26 + 1) {
			dsp->fVec5[l26] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l27;
		for (l27 = 0; l27 < 2; l27 = l27 + 1) {
			dsp->fRec28[l27] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l28;
		for (l28 = 0; l28 < 2; l28 = l28 + 1) {
			dsp->fRec31[l28] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l29;
		for (l29 = 0; l29 < 8192; l29 = l29 + 1) {
			dsp->fVec6[l29] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l30;
		for (l30 = 0; l30 < 2; l30 = l30 + 1) {
			dsp->fRec30[l30] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l31;
		for (l31 = 0; l31 < 2; l31 = l31 + 1) {
			dsp->fRec33[l31] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l32;
		for (l32 = 0; l32 < 8192; l32 = l32 + 1) {
			dsp->fVec7[l32] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l33;
		for (l33 = 0; l33 < 2; l33 = l33 + 1) {
			dsp->fRec32[l33] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l34;
		for (l34 = 0; l34 < 2; l34 = l34 + 1) {
			dsp->fRec35[l34] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l35;
		for (l35 = 0; l35 < 8192; l35 = l35 + 1) {
			dsp->fVec8[l35] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l36;
		for (l36 = 0; l36 < 2; l36 = l36 + 1) {
			dsp->fRec34[l36] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l37;
		for (l37 = 0; l37 < 2; l37 = l37 + 1) {
			dsp->fRec37[l37] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l38;
		for (l38 = 0; l38 < 8192; l38 = l38 + 1) {
			dsp->fVec9[l38] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l39;
		for (l39 = 0; l39 < 2; l39 = l39 + 1) {
			dsp->fRec36[l39] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l40;
		for (l40 = 0; l40 < 2; l40 = l40 + 1) {
			dsp->fRec39[l40] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l41;
		for (l41 = 0; l41 < 8192; l41 = l41 + 1) {
			dsp->fVec10[l41] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l42;
		for (l42 = 0; l42 < 2; l42 = l42 + 1) {
			dsp->fRec38[l42] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l43;
		for (l43 = 0; l43 < 2; l43 = l43 + 1) {
			dsp->fRec41[l43] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l44;
		for (l44 = 0; l44 < 8192; l44 = l44 + 1) {
			dsp->fVec11[l44] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l45;
		for (l45 = 0; l45 < 2; l45 = l45 + 1) {
			dsp->fRec40[l45] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l46;
		for (l46 = 0; l46 < 2; l46 = l46 + 1) {
			dsp->fRec43[l46] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l47;
		for (l47 = 0; l47 < 8192; l47 = l47 + 1) {
			dsp->fVec12[l47] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l48;
		for (l48 = 0; l48 < 2; l48 = l48 + 1) {
			dsp->fRec42[l48] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l49;
		for (l49 = 0; l49 < 2048; l49 = l49 + 1) {
			dsp->fVec13[l49] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l50;
		for (l50 = 0; l50 < 2; l50 = l50 + 1) {
			dsp->fRec26[l50] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l51;
		for (l51 = 0; l51 < 2048; l51 = l51 + 1) {
			dsp->fVec14[l51] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l52;
		for (l52 = 0; l52 < 2; l52 = l52 + 1) {
			dsp->fRec24[l52] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l53;
		for (l53 = 0; l53 < 2048; l53 = l53 + 1) {
			dsp->fVec15[l53] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l54;
		for (l54 = 0; l54 < 2; l54 = l54 + 1) {
			dsp->fRec22[l54] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l55;
		for (l55 = 0; l55 < 1024; l55 = l55 + 1) {
			dsp->fVec16[l55] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l56;
		for (l56 = 0; l56 < 2; l56 = l56 + 1) {
			dsp->fRec20[l56] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l57;
		for (l57 = 0; l57 < 2; l57 = l57 + 1) {
			dsp->fRec53[l57] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l58;
		for (l58 = 0; l58 < 8192; l58 = l58 + 1) {
			dsp->fVec17[l58] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l59;
		for (l59 = 0; l59 < 2; l59 = l59 + 1) {
			dsp->fRec52[l59] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l60;
		for (l60 = 0; l60 < 2; l60 = l60 + 1) {
			dsp->fRec55[l60] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l61;
		for (l61 = 0; l61 < 8192; l61 = l61 + 1) {
			dsp->fVec18[l61] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l62;
		for (l62 = 0; l62 < 2; l62 = l62 + 1) {
			dsp->fRec54[l62] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l63;
		for (l63 = 0; l63 < 2; l63 = l63 + 1) {
			dsp->fRec57[l63] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l64;
		for (l64 = 0; l64 < 8192; l64 = l64 + 1) {
			dsp->fVec19[l64] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l65;
		for (l65 = 0; l65 < 2; l65 = l65 + 1) {
			dsp->fRec56[l65] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l66;
		for (l66 = 0; l66 < 2; l66 = l66 + 1) {
			dsp->fRec59[l66] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l67;
		for (l67 = 0; l67 < 8192; l67 = l67 + 1) {
			dsp->fVec20[l67] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l68;
		for (l68 = 0; l68 < 2; l68 = l68 + 1) {
			dsp->fRec58[l68] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l69;
		for (l69 = 0; l69 < 2; l69 = l69 + 1) {
			dsp->fRec61[l69] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l70;
		for (l70 = 0; l70 < 8192; l70 = l70 + 1) {
			dsp->fVec21[l70] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l71;
		for (l71 = 0; l71 < 2; l71 = l71 + 1) {
			dsp->fRec60[l71] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l72;
		for (l72 = 0; l72 < 2; l72 = l72 + 1) {
			dsp->fRec63[l72] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l73;
		for (l73 = 0; l73 < 8192; l73 = l73 + 1) {
			dsp->fVec22[l73] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l74;
		for (l74 = 0; l74 < 2; l74 = l74 + 1) {
			dsp->fRec62[l74] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l75;
		for (l75 = 0; l75 < 2; l75 = l75 + 1) {
			dsp->fRec65[l75] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l76;
		for (l76 = 0; l76 < 8192; l76 = l76 + 1) {
			dsp->fVec23[l76] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l77;
		for (l77 = 0; l77 < 2; l77 = l77 + 1) {
			dsp->fRec64[l77] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l78;
		for (l78 = 0; l78 < 2; l78 = l78 + 1) {
			dsp->fRec67[l78] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l79;
		for (l79 = 0; l79 < 8192; l79 = l79 + 1) {
			dsp->fVec24[l79] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l80;
		for (l80 = 0; l80 < 2; l80 = l80 + 1) {
			dsp->fRec66[l80] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l81;
		for (l81 = 0; l81 < 2048; l81 = l81 + 1) {
			dsp->fVec25[l81] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l82;
		for (l82 = 0; l82 < 2; l82 = l82 + 1) {
			dsp->fRec50[l82] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l83;
		for (l83 = 0; l83 < 2048; l83 = l83 + 1) {
			dsp->fVec26[l83] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l84;
		for (l84 = 0; l84 < 2; l84 = l84 + 1) {
			dsp->fRec48[l84] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l85;
		for (l85 = 0; l85 < 2048; l85 = l85 + 1) {
			dsp->fVec27[l85] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l86;
		for (l86 = 0; l86 < 2; l86 = l86 + 1) {
			dsp->fRec46[l86] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l87;
		for (l87 = 0; l87 < 1024; l87 = l87 + 1) {
			dsp->fVec28[l87] = 0.0f;
		}
	}
	/* C99 loop */
	{
		int l88;
		for (l88 = 0; l88 < 2; l88 = l88 + 1) {
			dsp->fRec44[l88] = 0.0f;
		}
	}
}

void instanceConstantstrail_faust(trail_faust* dsp, int sample_rate) {
	dsp->fSampleRate = sample_rate;
	dsp->fConst0 = fminf(1.92e+05f, fmaxf(1.0f, (float)(dsp->fSampleRate)));
	dsp->fConst1 = expf(-(5e+01f / dsp->fConst0));
	dsp->fConst2 = 0.012f * dsp->fConst0;
	dsp->fConst3 = 0.35f / dsp->fConst0;
	dsp->fConst4 = 3.1415927f / dsp->fConst0;
	dsp->fConst5 = 0.49f * dsp->fConst0;
	dsp->fConst6 = 0.3395f / dsp->fConst0;
	dsp->iConst7 = (int)(0.036666665f * dsp->fConst0);
	dsp->iConst8 = faustmaxi(0, dsp->iConst7 + -1);
	dsp->iConst9 = (int)(0.035306122f * dsp->fConst0);
	dsp->iConst10 = faustmaxi(0, dsp->iConst9 + -1);
	dsp->iConst11 = (int)(0.033809524f * dsp->fConst0);
	dsp->iConst12 = faustmaxi(0, dsp->iConst11 + -1);
	dsp->iConst13 = (int)(0.0322449f * dsp->fConst0);
	dsp->iConst14 = faustmaxi(0, dsp->iConst13 + -1);
	dsp->iConst15 = (int)(0.030748298f * dsp->fConst0);
	dsp->iConst16 = faustmaxi(0, dsp->iConst15 + -1);
	dsp->iConst17 = (int)(0.028956916f * dsp->fConst0);
	dsp->iConst18 = faustmaxi(0, dsp->iConst17 + -1);
	dsp->iConst19 = (int)(0.026938776f * dsp->fConst0);
	dsp->iConst20 = faustmaxi(0, dsp->iConst19 + -1);
	dsp->iConst21 = (int)(0.025306122f * dsp->fConst0);
	dsp->iConst22 = faustmaxi(0, dsp->iConst21 + -1);
	dsp->iConst23 = (int)(0.0126077095f * dsp->fConst0);
	dsp->iConst24 = faustmini(1024, faustmaxi(0, dsp->iConst23 + -1));
	dsp->iConst25 = (int)(0.01f * dsp->fConst0);
	dsp->iConst26 = faustmini(1024, faustmaxi(0, dsp->iConst25 + -1));
	dsp->iConst27 = (int)(0.0077324263f * dsp->fConst0);
	dsp->iConst28 = faustmini(1024, faustmaxi(0, dsp->iConst27 + -1));
	dsp->iConst29 = (int)(0.0051020407f * dsp->fConst0);
	dsp->iConst30 = faustmini(1024, faustmaxi(0, dsp->iConst29 + -1));
	dsp->iConst31 = faustmaxi(0, dsp->iConst7 + 22);
	dsp->iConst32 = faustmaxi(0, dsp->iConst9 + 22);
	dsp->iConst33 = faustmaxi(0, dsp->iConst11 + 22);
	dsp->iConst34 = faustmaxi(0, dsp->iConst13 + 22);
	dsp->iConst35 = faustmaxi(0, dsp->iConst15 + 22);
	dsp->iConst36 = faustmaxi(0, dsp->iConst17 + 22);
	dsp->iConst37 = faustmaxi(0, dsp->iConst19 + 22);
	dsp->iConst38 = faustmaxi(0, dsp->iConst21 + 22);
	dsp->iConst39 = faustmini(1024, faustmaxi(0, dsp->iConst23 + 22));
	dsp->iConst40 = faustmini(1024, faustmaxi(0, dsp->iConst25 + 22));
	dsp->iConst41 = faustmini(1024, faustmaxi(0, dsp->iConst27 + 22));
	dsp->iConst42 = faustmini(1024, faustmaxi(0, dsp->iConst29 + 22));
}
	
void instanceInittrail_faust(trail_faust* dsp, int sample_rate) {
	instanceConstantstrail_faust(dsp, sample_rate);
	instanceResetUserInterfacetrail_faust(dsp);
	instanceCleartrail_faust(dsp);
}

void inittrail_faust(trail_faust* dsp, int sample_rate) {
	classInittrail_faust(sample_rate);
	instanceInittrail_faust(dsp, sample_rate);
}

void buildUserInterfacetrail_faust(trail_faust* dsp, UIGlue* ui_interface) {
	ui_interface->openVerticalBox(ui_interface->uiInterface, "trail");
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "_dtime", &dsp->fHslider1, (FAUSTFLOAT)1.323e+04f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)131064.0f, (FAUSTFLOAT)1.0f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "drive", &dsp->fHslider6, (FAUSTFLOAT)0.12f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "feedback", &dsp->fHslider3, (FAUSTFLOAT)0.22f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)0.88f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "mix", &dsp->fHslider0, (FAUSTFLOAT)0.18f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "mod", &dsp->fHslider2, (FAUSTFLOAT)0.12f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "space", &dsp->fHslider7, (FAUSTFLOAT)0.05f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "tone", &dsp->fHslider5, (FAUSTFLOAT)0.55f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->addHorizontalSlider(ui_interface->uiInterface, "width", &dsp->fHslider4, (FAUSTFLOAT)0.5f, (FAUSTFLOAT)0.0f, (FAUSTFLOAT)1.0f, (FAUSTFLOAT)0.01f);
	ui_interface->closeBox(ui_interface->uiInterface);
}

void computetrail_faust(trail_faust* dsp, int count, FAUSTFLOAT** RESTRICT inputs, FAUSTFLOAT** RESTRICT outputs) {
	FAUSTFLOAT* input0 = inputs[0];
	FAUSTFLOAT* input1 = inputs[1];
	FAUSTFLOAT* output0 = outputs[0];
	FAUSTFLOAT* output1 = outputs[1];
	float fSlow0 = (float)(dsp->fHslider0);
	float fSlow1 = (float)(dsp->fHslider1);
	float fSlow2 = (float)(dsp->fHslider2);
	float fSlow3 = (float)(dsp->fHslider3);
	float fSlow4 = (float)(dsp->fHslider4);
	float fSlow5 = (float)(dsp->fHslider5);
	float fSlow6 = tanf(dsp->fConst4 * fmaxf(1.0f, fminf(1.1e+04f * trail_faust_faustpower2_f(fSlow5) + 3.5e+02f, dsp->fConst5)));
	float fSlow7 = fSlow6 + 1.0f;
	float fSlow8 = fSlow6 / fSlow7;
	float fSlow9 = tanf(dsp->fConst4 * fmaxf(1.0f, fminf(275.0f * (1.0f - fSlow5) + 25.0f, dsp->fConst5)));
	float fSlow10 = fSlow9 + 1.0f;
	float fSlow11 = 1.0f / fSlow10;
	float fSlow12 = (fSlow9 + -1.0f) / fSlow10;
	float fSlow13 = (fSlow6 + -1.0f) / fSlow7;
	float fSlow14 = (float)(dsp->fHslider6);
	float fSlow15 = (float)(dsp->fHslider7);
	/* C99 loop */
	{
		int i0;
		for (i0 = 0; i0 < count; i0 = i0 + 1) {
			float fTemp0 = (float)(input0[i0]);
			dsp->fVec0[0] = 1.0f;
			dsp->iVec1[0] = 1;
			float fTemp1 = 1.0f - dsp->fConst1 * dsp->fVec0[1];
			float fTemp2 = fSlow0 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec0[1];
			dsp->fRec0[0] = ((fabsf(fTemp2) > 1.1754944e-38f) ? fTemp2 : 0.0f);
			float fTemp3 = 1.0f - dsp->fRec0[0];
			float fTemp4 = fSlow2 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec3[1];
			dsp->fRec3[0] = ((fabsf(fTemp4) > 1.1754944e-38f) ? fTemp4 : 0.0f);
			int iTemp5 = 1 - dsp->iVec1[1];
			float fTemp6 = ((iTemp5) ? 0.0f : dsp->fConst3 + dsp->fRec5[1]);
			float fTemp7 = fTemp6 - floorf(fTemp6);
			dsp->fRec5[0] = ((fabsf(fTemp7) > 1.1754944e-38f) ? fTemp7 : 0.0f);
			float fTemp8 = fmaxf(64.0f, fSlow1 + dsp->fConst2 * dsp->fRec3[0] * ftbl0trail_faustSIG0[faustmaxi(0, faustmini((int)(65536.0f * dsp->fRec5[0]), 65535))]);
			float fTemp9 = fTemp8 + -1.499995f;
			float fTemp10 = floorf(fTemp9);
			float fTemp11 = fTemp8 + (-3.0f - fTemp10);
			float fTemp12 = fTemp8 + (-2.0f - fTemp10);
			float fTemp13 = fSlow3 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec6[1];
			dsp->fRec6[0] = ((fabsf(fTemp13) > 1.1754944e-38f) ? fTemp13 : 0.0f);
			float fTemp14 = fSlow4 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec7[1];
			dsp->fRec7[0] = ((fabsf(fTemp14) > 1.1754944e-38f) ? fTemp14 : 0.0f);
			float fTemp15 = 1.0f - dsp->fRec7[0];
			float fTemp16 = fSlow8 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec9[1];
			dsp->fRec9[0] = ((fabsf(fTemp16) > 1.1754944e-38f) ? fTemp16 : 0.0f);
			float fTemp17 = fSlow11 * fTemp1;
			float fTemp18 = fTemp17 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec11[1];
			dsp->fRec11[0] = ((fabsf(fTemp18) > 1.1754944e-38f) ? fTemp18 : 0.0f);
			float fTemp19 = dsp->fConst1 * dsp->fVec0[1] * dsp->fRec12[1] - fTemp17;
			dsp->fRec12[0] = ((fabsf(fTemp19) > 1.1754944e-38f) ? fTemp19 : 0.0f);
			float fTemp20 = fSlow12 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec13[1];
			dsp->fRec13[0] = ((fabsf(fTemp20) > 1.1754944e-38f) ? fTemp20 : 0.0f);
			float fTemp21 = dsp->fRec11[0] * dsp->fRec1[1] + dsp->fRec12[0] * dsp->fRec1[2] - dsp->fRec13[0] * dsp->fRec10[1];
			dsp->fRec10[0] = ((fabsf(fTemp21) > 1.1754944e-38f) ? fTemp21 : 0.0f);
			float fTemp22 = fSlow13 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec14[1];
			dsp->fRec14[0] = ((fabsf(fTemp22) > 1.1754944e-38f) ? fTemp22 : 0.0f);
			float fTemp23 = dsp->fRec9[0] * (dsp->fRec10[0] + dsp->fRec10[1]) - dsp->fRec14[0] * dsp->fRec8[1];
			dsp->fRec8[0] = ((fabsf(fTemp23) > 1.1754944e-38f) ? fTemp23 : 0.0f);
			float fTemp24 = fSlow14 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec15[1];
			dsp->fRec15[0] = ((fabsf(fTemp24) > 1.1754944e-38f) ? fTemp24 : 0.0f);
			float fTemp25 = 4.0f * dsp->fRec15[0] + 1.0f;
			float fTemp26 = tanhf(dsp->fRec8[0] * fTemp25);
			float fTemp27 = dsp->fRec11[0] * dsp->fRec2[1] + dsp->fRec12[0] * dsp->fRec2[2] - dsp->fRec13[0] * dsp->fRec17[1];
			dsp->fRec17[0] = ((fabsf(fTemp27) > 1.1754944e-38f) ? fTemp27 : 0.0f);
			float fTemp28 = dsp->fRec9[0] * (dsp->fRec17[0] + dsp->fRec17[1]) - dsp->fRec14[0] * dsp->fRec16[1];
			dsp->fRec16[0] = ((fabsf(fTemp28) > 1.1754944e-38f) ? fTemp28 : 0.0f);
			float fTemp29 = tanhf(dsp->fRec16[0] * fTemp25);
			float fTemp30 = 1.5f * dsp->fRec15[0] + 1.0f;
			float fTemp31 = fTemp0 + dsp->fRec6[0] * (fTemp15 * fTemp26 + dsp->fRec7[0] * fTemp29) / fTemp30;
			dsp->fVec3[dsp->IOTA0 & 262143] = fTemp31;
			int iTemp32 = (int)(fTemp9);
			float fTemp33 = fTemp8 + (-1.0f - fTemp10);
			float fTemp34 = fTemp8 - fTemp10;
			float fTemp35 = fTemp34 * fTemp33;
			float fTemp36 = fTemp35 * fTemp12;
			float fTemp37 = (fTemp8 + (-4.0f - fTemp10)) * (fTemp11 * (fTemp12 * (0.041666668f * dsp->fVec3[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp32))) & 262143] * fTemp33 - 0.16666667f * fTemp34 * dsp->fVec3[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp32 + 1))) & 262143]) + 0.25f * fTemp35 * dsp->fVec3[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp32 + 2))) & 262143]) - 0.16666667f * fTemp36 * dsp->fVec3[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp32 + 3))) & 262143]) + 0.041666668f * fTemp36 * fTemp11 * dsp->fVec3[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp32 + 4))) & 262143];
			dsp->fRec1[0] = ((fabsf(fTemp37) > 1.1754944e-38f) ? fTemp37 : 0.0f);
			float fTemp38 = ((iTemp5) ? 0.0f : dsp->fConst6 + dsp->fRec18[1]);
			float fTemp39 = fTemp38 - floorf(fTemp38);
			dsp->fRec18[0] = ((fabsf(fTemp39) > 1.1754944e-38f) ? fTemp39 : 0.0f);
			float fTemp40 = fmaxf(64.0f, fSlow1 + dsp->fConst2 * dsp->fRec3[0] * ftbl0trail_faustSIG0[faustmaxi(0, faustmini((int)(65536.0f * dsp->fRec18[0]), 65535))]);
			float fTemp41 = fTemp40 + -1.499995f;
			float fTemp42 = floorf(fTemp41);
			float fTemp43 = fTemp40 + (-3.0f - fTemp42);
			float fTemp44 = fTemp40 + (-2.0f - fTemp42);
			float fTemp45 = (float)(input1[i0]);
			float fTemp46 = fTemp45 + dsp->fRec6[0] * (fTemp15 * fTemp29 + dsp->fRec7[0] * fTemp26) / fTemp30;
			dsp->fVec4[dsp->IOTA0 & 262143] = fTemp46;
			int iTemp47 = (int)(fTemp41);
			float fTemp48 = fTemp40 + (-1.0f - fTemp42);
			float fTemp49 = fTemp40 - fTemp42;
			float fTemp50 = fTemp49 * fTemp48;
			float fTemp51 = fTemp50 * fTemp44;
			float fTemp52 = (fTemp40 + (-4.0f - fTemp42)) * (fTemp43 * (fTemp44 * (0.041666668f * dsp->fVec4[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp47))) & 262143] * fTemp48 - 0.16666667f * fTemp49 * dsp->fVec4[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp47 + 1))) & 262143]) + 0.25f * fTemp50 * dsp->fVec4[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp47 + 2))) & 262143]) - 0.16666667f * fTemp51 * dsp->fVec4[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp47 + 3))) & 262143]) + 0.041666668f * fTemp51 * fTemp43 * dsp->fVec4[(dsp->IOTA0 - faustmini(131072, faustmaxi(0, iTemp47 + 4))) & 262143];
			dsp->fRec2[0] = ((fabsf(fTemp52) > 1.1754944e-38f) ? fTemp52 : 0.0f);
			float fTemp53 = fSlow15 * fTemp1 + dsp->fConst1 * dsp->fVec0[1] * dsp->fRec19[1];
			dsp->fRec19[0] = ((fabsf(fTemp53) > 1.1754944e-38f) ? fTemp53 : 0.0f);
			float fTemp54 = 1.0f - dsp->fRec19[0];
			float fTemp55 = 0.1f * (dsp->fRec1[0] + dsp->fRec2[0]);
			float fTemp56 = 0.4f * dsp->fRec29[1] + 0.6f * dsp->fRec28[1];
			dsp->fRec29[0] = ((fabsf(fTemp56) > 1.1754944e-38f) ? fTemp56 : 0.0f);
			dsp->fVec5[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec29[0];
			float fTemp57 = dsp->fVec5[(dsp->IOTA0 - dsp->iConst8) & 8191];
			dsp->fRec28[0] = ((fabsf(fTemp57) > 1.1754944e-38f) ? fTemp57 : 0.0f);
			float fTemp58 = 0.4f * dsp->fRec31[1] + 0.6f * dsp->fRec30[1];
			dsp->fRec31[0] = ((fabsf(fTemp58) > 1.1754944e-38f) ? fTemp58 : 0.0f);
			dsp->fVec6[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec31[0];
			float fTemp59 = dsp->fVec6[(dsp->IOTA0 - dsp->iConst10) & 8191];
			dsp->fRec30[0] = ((fabsf(fTemp59) > 1.1754944e-38f) ? fTemp59 : 0.0f);
			float fTemp60 = 0.4f * dsp->fRec33[1] + 0.6f * dsp->fRec32[1];
			dsp->fRec33[0] = ((fabsf(fTemp60) > 1.1754944e-38f) ? fTemp60 : 0.0f);
			dsp->fVec7[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec33[0];
			float fTemp61 = dsp->fVec7[(dsp->IOTA0 - dsp->iConst12) & 8191];
			dsp->fRec32[0] = ((fabsf(fTemp61) > 1.1754944e-38f) ? fTemp61 : 0.0f);
			float fTemp62 = 0.4f * dsp->fRec35[1] + 0.6f * dsp->fRec34[1];
			dsp->fRec35[0] = ((fabsf(fTemp62) > 1.1754944e-38f) ? fTemp62 : 0.0f);
			dsp->fVec8[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec35[0];
			float fTemp63 = dsp->fVec8[(dsp->IOTA0 - dsp->iConst14) & 8191];
			dsp->fRec34[0] = ((fabsf(fTemp63) > 1.1754944e-38f) ? fTemp63 : 0.0f);
			float fTemp64 = 0.4f * dsp->fRec37[1] + 0.6f * dsp->fRec36[1];
			dsp->fRec37[0] = ((fabsf(fTemp64) > 1.1754944e-38f) ? fTemp64 : 0.0f);
			dsp->fVec9[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec37[0];
			float fTemp65 = dsp->fVec9[(dsp->IOTA0 - dsp->iConst16) & 8191];
			dsp->fRec36[0] = ((fabsf(fTemp65) > 1.1754944e-38f) ? fTemp65 : 0.0f);
			float fTemp66 = 0.4f * dsp->fRec39[1] + 0.6f * dsp->fRec38[1];
			dsp->fRec39[0] = ((fabsf(fTemp66) > 1.1754944e-38f) ? fTemp66 : 0.0f);
			dsp->fVec10[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec39[0];
			float fTemp67 = dsp->fVec10[(dsp->IOTA0 - dsp->iConst18) & 8191];
			dsp->fRec38[0] = ((fabsf(fTemp67) > 1.1754944e-38f) ? fTemp67 : 0.0f);
			float fTemp68 = 0.4f * dsp->fRec41[1] + 0.6f * dsp->fRec40[1];
			dsp->fRec41[0] = ((fabsf(fTemp68) > 1.1754944e-38f) ? fTemp68 : 0.0f);
			dsp->fVec11[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec41[0];
			float fTemp69 = dsp->fVec11[(dsp->IOTA0 - dsp->iConst20) & 8191];
			dsp->fRec40[0] = ((fabsf(fTemp69) > 1.1754944e-38f) ? fTemp69 : 0.0f);
			float fTemp70 = 0.4f * dsp->fRec43[1] + 0.6f * dsp->fRec42[1];
			dsp->fRec43[0] = ((fabsf(fTemp70) > 1.1754944e-38f) ? fTemp70 : 0.0f);
			dsp->fVec12[dsp->IOTA0 & 8191] = 0.88f * dsp->fRec43[0] + fTemp55;
			float fTemp71 = dsp->fVec12[(dsp->IOTA0 - dsp->iConst22) & 8191];
			dsp->fRec42[0] = ((fabsf(fTemp71) > 1.1754944e-38f) ? fTemp71 : 0.0f);
			float fTemp72 = dsp->fRec28[1] + dsp->fRec30[1] + dsp->fRec32[1] + dsp->fRec34[1] + dsp->fRec36[1] + dsp->fRec38[1] + dsp->fRec40[1] + 0.5f * dsp->fRec26[1] + dsp->fRec42[1];
			dsp->fVec13[dsp->IOTA0 & 2047] = fTemp72;
			float fTemp73 = dsp->fVec13[(dsp->IOTA0 - dsp->iConst24) & 2047];
			dsp->fRec26[0] = ((fabsf(fTemp73) > 1.1754944e-38f) ? fTemp73 : 0.0f);
			float fTemp74 = 0.5f * fTemp72;
			float fRec27 = ((fabsf(-fTemp74) > 1.1754944e-38f) ? -fTemp74 : 0.0f);
			float fTemp75 = dsp->fRec26[1] + fRec27 + 0.5f * dsp->fRec24[1];
			dsp->fVec14[dsp->IOTA0 & 2047] = fTemp75;
			float fTemp76 = dsp->fVec14[(dsp->IOTA0 - dsp->iConst26) & 2047];
			dsp->fRec24[0] = ((fabsf(fTemp76) > 1.1754944e-38f) ? fTemp76 : 0.0f);
			float fTemp77 = 0.5f * fTemp75;
			float fRec25 = ((fabsf(-fTemp77) > 1.1754944e-38f) ? -fTemp77 : 0.0f);
			float fTemp78 = dsp->fRec24[1] + fRec25 + 0.5f * dsp->fRec22[1];
			dsp->fVec15[dsp->IOTA0 & 2047] = fTemp78;
			float fTemp79 = dsp->fVec15[(dsp->IOTA0 - dsp->iConst28) & 2047];
			dsp->fRec22[0] = ((fabsf(fTemp79) > 1.1754944e-38f) ? fTemp79 : 0.0f);
			float fTemp80 = 0.5f * fTemp78;
			float fRec23 = ((fabsf(-fTemp80) > 1.1754944e-38f) ? -fTemp80 : 0.0f);
			float fTemp81 = dsp->fRec22[1] + fRec23 + 0.5f * dsp->fRec20[1];
			dsp->fVec16[dsp->IOTA0 & 1023] = fTemp81;
			float fTemp82 = dsp->fVec16[(dsp->IOTA0 - dsp->iConst30) & 1023];
			dsp->fRec20[0] = ((fabsf(fTemp82) > 1.1754944e-38f) ? fTemp82 : 0.0f);
			float fTemp83 = 0.5f * fTemp81;
			float fRec21 = ((fabsf(-fTemp83) > 1.1754944e-38f) ? -fTemp83 : 0.0f);
			float fTemp84 = fTemp0 * fTemp3 + dsp->fRec0[0] * (dsp->fRec1[0] * fTemp54 + dsp->fRec19[0] * (fRec21 + dsp->fRec20[1]));
			output0[i0] = (FAUSTFLOAT)(fTemp84 / fmaxf(1.0f, 1.0526316f * fabsf(fTemp84)));
			float fTemp85 = 0.4f * dsp->fRec53[1] + 0.6f * dsp->fRec52[1];
			dsp->fRec53[0] = ((fabsf(fTemp85) > 1.1754944e-38f) ? fTemp85 : 0.0f);
			dsp->fVec17[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec53[0];
			float fTemp86 = dsp->fVec17[(dsp->IOTA0 - dsp->iConst31) & 8191];
			dsp->fRec52[0] = ((fabsf(fTemp86) > 1.1754944e-38f) ? fTemp86 : 0.0f);
			float fTemp87 = 0.4f * dsp->fRec55[1] + 0.6f * dsp->fRec54[1];
			dsp->fRec55[0] = ((fabsf(fTemp87) > 1.1754944e-38f) ? fTemp87 : 0.0f);
			dsp->fVec18[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec55[0];
			float fTemp88 = dsp->fVec18[(dsp->IOTA0 - dsp->iConst32) & 8191];
			dsp->fRec54[0] = ((fabsf(fTemp88) > 1.1754944e-38f) ? fTemp88 : 0.0f);
			float fTemp89 = 0.4f * dsp->fRec57[1] + 0.6f * dsp->fRec56[1];
			dsp->fRec57[0] = ((fabsf(fTemp89) > 1.1754944e-38f) ? fTemp89 : 0.0f);
			dsp->fVec19[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec57[0];
			float fTemp90 = dsp->fVec19[(dsp->IOTA0 - dsp->iConst33) & 8191];
			dsp->fRec56[0] = ((fabsf(fTemp90) > 1.1754944e-38f) ? fTemp90 : 0.0f);
			float fTemp91 = 0.4f * dsp->fRec59[1] + 0.6f * dsp->fRec58[1];
			dsp->fRec59[0] = ((fabsf(fTemp91) > 1.1754944e-38f) ? fTemp91 : 0.0f);
			dsp->fVec20[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec59[0];
			float fTemp92 = dsp->fVec20[(dsp->IOTA0 - dsp->iConst34) & 8191];
			dsp->fRec58[0] = ((fabsf(fTemp92) > 1.1754944e-38f) ? fTemp92 : 0.0f);
			float fTemp93 = 0.4f * dsp->fRec61[1] + 0.6f * dsp->fRec60[1];
			dsp->fRec61[0] = ((fabsf(fTemp93) > 1.1754944e-38f) ? fTemp93 : 0.0f);
			dsp->fVec21[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec61[0];
			float fTemp94 = dsp->fVec21[(dsp->IOTA0 - dsp->iConst35) & 8191];
			dsp->fRec60[0] = ((fabsf(fTemp94) > 1.1754944e-38f) ? fTemp94 : 0.0f);
			float fTemp95 = 0.4f * dsp->fRec63[1] + 0.6f * dsp->fRec62[1];
			dsp->fRec63[0] = ((fabsf(fTemp95) > 1.1754944e-38f) ? fTemp95 : 0.0f);
			dsp->fVec22[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec63[0];
			float fTemp96 = dsp->fVec22[(dsp->IOTA0 - dsp->iConst36) & 8191];
			dsp->fRec62[0] = ((fabsf(fTemp96) > 1.1754944e-38f) ? fTemp96 : 0.0f);
			float fTemp97 = 0.4f * dsp->fRec65[1] + 0.6f * dsp->fRec64[1];
			dsp->fRec65[0] = ((fabsf(fTemp97) > 1.1754944e-38f) ? fTemp97 : 0.0f);
			dsp->fVec23[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec65[0];
			float fTemp98 = dsp->fVec23[(dsp->IOTA0 - dsp->iConst37) & 8191];
			dsp->fRec64[0] = ((fabsf(fTemp98) > 1.1754944e-38f) ? fTemp98 : 0.0f);
			float fTemp99 = 0.4f * dsp->fRec67[1] + 0.6f * dsp->fRec66[1];
			dsp->fRec67[0] = ((fabsf(fTemp99) > 1.1754944e-38f) ? fTemp99 : 0.0f);
			dsp->fVec24[dsp->IOTA0 & 8191] = fTemp55 + 0.88f * dsp->fRec67[0];
			float fTemp100 = dsp->fVec24[(dsp->IOTA0 - dsp->iConst38) & 8191];
			dsp->fRec66[0] = ((fabsf(fTemp100) > 1.1754944e-38f) ? fTemp100 : 0.0f);
			float fTemp101 = dsp->fRec52[1] + dsp->fRec54[1] + dsp->fRec56[1] + dsp->fRec58[1] + dsp->fRec60[1] + dsp->fRec62[1] + dsp->fRec64[1] + 0.5f * dsp->fRec50[1] + dsp->fRec66[1];
			dsp->fVec25[dsp->IOTA0 & 2047] = fTemp101;
			float fTemp102 = dsp->fVec25[(dsp->IOTA0 - dsp->iConst39) & 2047];
			dsp->fRec50[0] = ((fabsf(fTemp102) > 1.1754944e-38f) ? fTemp102 : 0.0f);
			float fTemp103 = 0.5f * fTemp101;
			float fRec51 = ((fabsf(-fTemp103) > 1.1754944e-38f) ? -fTemp103 : 0.0f);
			float fTemp104 = dsp->fRec50[1] + fRec51 + 0.5f * dsp->fRec48[1];
			dsp->fVec26[dsp->IOTA0 & 2047] = fTemp104;
			float fTemp105 = dsp->fVec26[(dsp->IOTA0 - dsp->iConst40) & 2047];
			dsp->fRec48[0] = ((fabsf(fTemp105) > 1.1754944e-38f) ? fTemp105 : 0.0f);
			float fTemp106 = 0.5f * fTemp104;
			float fRec49 = ((fabsf(-fTemp106) > 1.1754944e-38f) ? -fTemp106 : 0.0f);
			float fTemp107 = dsp->fRec48[1] + fRec49 + 0.5f * dsp->fRec46[1];
			dsp->fVec27[dsp->IOTA0 & 2047] = fTemp107;
			float fTemp108 = dsp->fVec27[(dsp->IOTA0 - dsp->iConst41) & 2047];
			dsp->fRec46[0] = ((fabsf(fTemp108) > 1.1754944e-38f) ? fTemp108 : 0.0f);
			float fTemp109 = 0.5f * fTemp107;
			float fRec47 = ((fabsf(-fTemp109) > 1.1754944e-38f) ? -fTemp109 : 0.0f);
			float fTemp110 = dsp->fRec46[1] + fRec47 + 0.5f * dsp->fRec44[1];
			dsp->fVec28[dsp->IOTA0 & 1023] = fTemp110;
			float fTemp111 = dsp->fVec28[(dsp->IOTA0 - dsp->iConst42) & 1023];
			dsp->fRec44[0] = ((fabsf(fTemp111) > 1.1754944e-38f) ? fTemp111 : 0.0f);
			float fTemp112 = 0.5f * fTemp110;
			float fRec45 = ((fabsf(-fTemp112) > 1.1754944e-38f) ? -fTemp112 : 0.0f);
			float fTemp113 = fTemp45 * fTemp3 + dsp->fRec0[0] * (fTemp54 * dsp->fRec2[0] + dsp->fRec19[0] * (fRec45 + dsp->fRec44[1]));
			output1[i0] = (FAUSTFLOAT)(fTemp113 / fmaxf(1.0f, 1.0526316f * fabsf(fTemp113)));
			dsp->fVec0[1] = dsp->fVec0[0];
			dsp->iVec1[1] = dsp->iVec1[0];
			dsp->fRec0[1] = dsp->fRec0[0];
			dsp->fRec3[1] = dsp->fRec3[0];
			dsp->fRec5[1] = dsp->fRec5[0];
			dsp->fRec6[1] = dsp->fRec6[0];
			dsp->fRec7[1] = dsp->fRec7[0];
			dsp->fRec9[1] = dsp->fRec9[0];
			dsp->fRec11[1] = dsp->fRec11[0];
			dsp->fRec12[1] = dsp->fRec12[0];
			dsp->fRec13[1] = dsp->fRec13[0];
			dsp->fRec10[1] = dsp->fRec10[0];
			dsp->fRec14[1] = dsp->fRec14[0];
			dsp->fRec8[1] = dsp->fRec8[0];
			dsp->fRec15[1] = dsp->fRec15[0];
			dsp->fRec17[1] = dsp->fRec17[0];
			dsp->fRec16[1] = dsp->fRec16[0];
			dsp->IOTA0 = dsp->IOTA0 + 1;
			dsp->fRec1[2] = dsp->fRec1[1];
			dsp->fRec1[1] = dsp->fRec1[0];
			dsp->fRec18[1] = dsp->fRec18[0];
			dsp->fRec2[2] = dsp->fRec2[1];
			dsp->fRec2[1] = dsp->fRec2[0];
			dsp->fRec19[1] = dsp->fRec19[0];
			dsp->fRec29[1] = dsp->fRec29[0];
			dsp->fRec28[1] = dsp->fRec28[0];
			dsp->fRec31[1] = dsp->fRec31[0];
			dsp->fRec30[1] = dsp->fRec30[0];
			dsp->fRec33[1] = dsp->fRec33[0];
			dsp->fRec32[1] = dsp->fRec32[0];
			dsp->fRec35[1] = dsp->fRec35[0];
			dsp->fRec34[1] = dsp->fRec34[0];
			dsp->fRec37[1] = dsp->fRec37[0];
			dsp->fRec36[1] = dsp->fRec36[0];
			dsp->fRec39[1] = dsp->fRec39[0];
			dsp->fRec38[1] = dsp->fRec38[0];
			dsp->fRec41[1] = dsp->fRec41[0];
			dsp->fRec40[1] = dsp->fRec40[0];
			dsp->fRec43[1] = dsp->fRec43[0];
			dsp->fRec42[1] = dsp->fRec42[0];
			dsp->fRec26[1] = dsp->fRec26[0];
			dsp->fRec24[1] = dsp->fRec24[0];
			dsp->fRec22[1] = dsp->fRec22[0];
			dsp->fRec20[1] = dsp->fRec20[0];
			dsp->fRec53[1] = dsp->fRec53[0];
			dsp->fRec52[1] = dsp->fRec52[0];
			dsp->fRec55[1] = dsp->fRec55[0];
			dsp->fRec54[1] = dsp->fRec54[0];
			dsp->fRec57[1] = dsp->fRec57[0];
			dsp->fRec56[1] = dsp->fRec56[0];
			dsp->fRec59[1] = dsp->fRec59[0];
			dsp->fRec58[1] = dsp->fRec58[0];
			dsp->fRec61[1] = dsp->fRec61[0];
			dsp->fRec60[1] = dsp->fRec60[0];
			dsp->fRec63[1] = dsp->fRec63[0];
			dsp->fRec62[1] = dsp->fRec62[0];
			dsp->fRec65[1] = dsp->fRec65[0];
			dsp->fRec64[1] = dsp->fRec64[0];
			dsp->fRec67[1] = dsp->fRec67[0];
			dsp->fRec66[1] = dsp->fRec66[0];
			dsp->fRec50[1] = dsp->fRec50[0];
			dsp->fRec48[1] = dsp->fRec48[0];
			dsp->fRec46[1] = dsp->fRec46[0];
			dsp->fRec44[1] = dsp->fRec44[0];
		}
	}
}

#ifdef __cplusplus
}
#endif

#endif

#pragma GCC diagnostic pop
