import { readFile, writeFile } from "node:fs/promises";
import { modulePaths, selectedModuleIds } from "./lib/modules.ts";

type Param = { key: string };
type ModuleJson = {
  capabilities?: {
    ui_hierarchy?: {
      levels?: {
        root?: {
          params?: Param[];
        };
      };
    };
  };
  id: string;
};
type Preset = {
  name: string;
  params?: Record<string, number>;
};
type PresetsJson = {
  presets?: Preset[];
};

const mode = process.argv[2] === "--check" ? "check" : "write";
const moduleIds = await selectedModuleIds();

let drift = 0;
for (const moduleId of moduleIds) {
  const paths = modulePaths(moduleId);
  const moduleJson = JSON.parse(await readFile(paths.moduleJson, "utf8")) as ModuleJson;
  const params = moduleJson.capabilities?.ui_hierarchy?.levels?.root?.params;
  if (!params) {
    console.warn(`[${moduleId}] no capabilities.ui_hierarchy.levels.root.params — skipping`);
    continue;
  }

  const presetsJson = JSON.parse(await readFile(paths.presets, "utf8").catch(() => '{"presets":[]}')) as PresetsJson;
  const presets = presetsJson.presets ?? [];
  const generated = renderInc(moduleId, params, presets);
  const existing = await readFile(paths.presetsGenInc, "utf8").catch(() => "");

  if (mode === "check") {
    if (generated !== existing) {
      console.error(`[${moduleId}] ${paths.presetsGenInc} is stale — run \`mise run gen-presets\``);
      drift++;
    }
    continue;
  }

  if (existing === generated) {
    console.log(`[${moduleId}] ${paths.presetsGenInc} unchanged`);
    continue;
  }
  await writeFile(paths.presetsGenInc, generated);
  console.log(`[${moduleId}] wrote ${paths.presetsGenInc} (${presets.length} preset${presets.length === 1 ? "" : "s"})`);
}

if (mode === "check" && drift > 0) {
  process.exit(1);
}

function renderInc(moduleId: string, params: Param[], presets: Preset[]): string {
  const upper = moduleId.toUpperCase();
  const guard = `${upper}_PRESETS_GEN_INC`;
  const coreT = `${moduleId}_core_t`;
  const paramKeys = params.map((p) => `    "${escapeCString(p.key)}"`).join(",\n");
  const presetValues = presets
    .map((preset, index) => {
      const values = params.map((p) => {
        const value = preset.params?.[p.key];
        if (typeof value !== "number") {
          throw new Error(`[${moduleId}] preset ${preset.name} missing numeric param ${p.key}`);
        }
        return cf(value);
      });
      return `static const float ${moduleId}_preset_values_${index}[${params.length}] = { ${values.join(", ")} };`;
    })
    .join("\n");
  const presetTable = presets
    .map((preset, index) => `    { "${escapeCString(preset.name)}", ${moduleId}_preset_values_${index} }`)
    .join(",\n");

  return `/* GENERATED by scripts/gen-presets.ts from presets.json — do not edit. */
/* Regenerate with: mise run gen-presets (or: pnpm run gen-presets) */

#ifndef ${guard}
#define ${guard}

#define ${upper}_PRESET_COUNT ${presets.length}

typedef struct {
    const char *name;
    const float *values;
} ${moduleId}_preset_t;

static const char *${moduleId}_preset_param_keys[${params.length}] = {
${paramKeys}
};

${presetValues}

static const ${moduleId}_preset_t ${moduleId}_presets[${Math.max(presets.length, 1)}] = {
${presetTable || "    { \"\", 0 }"}
};

static int ${moduleId}_preset_count(void) {
    return ${upper}_PRESET_COUNT;
}

static const char *${moduleId}_preset_name(int index) {
    if (index < 0 || index >= ${upper}_PRESET_COUNT) return "";
    return ${moduleId}_presets[index].name;
}

static int ${moduleId}_clamp_preset_index(int index) {
    if (${upper}_PRESET_COUNT <= 0) return 0;
    if (index < 0) return 0;
    if (index >= ${upper}_PRESET_COUNT) return ${upper}_PRESET_COUNT - 1;
    return index;
}

static void ${moduleId}_apply_preset(${coreT} *s, int index) {
    if (!s || ${upper}_PRESET_COUNT <= 0) return;
    index = ${moduleId}_clamp_preset_index(index);
    const float *values = ${moduleId}_presets[index].values;
    if (!values) return;
    for (int i = 0; i < ${params.length}; i++) {
        ${moduleId}_set_param(s, ${moduleId}_param_id(${moduleId}_preset_param_keys[i]), values[i]);
    }
}

#endif
`;
}

function escapeCString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, "\\\"");
}

function cf(value: number): string {
  if (!Number.isFinite(value)) throw new Error(`non-finite preset value: ${value}`);
  const s = Number(value.toPrecision(9)).toString();
  return s.includes(".") || s.includes("e") || s.includes("E") ? `${s}f` : `${s}.0f`;
}
