import { readFile, writeFile, stat, mkdtemp, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { modulePaths, selectedModuleIds } from "./lib/modules.ts";

const ARCH_FILE = "src/host/faust_module_arch.c.in";

const mode = process.argv[2] === "--check" ? "check" : "write";
const moduleIds = await selectedModuleIds();

let drift = 0;
let any = 0;

for (const moduleId of moduleIds) {
  const paths = modulePaths(moduleId);
  const dspPath = `${paths.moduleDir}/dsp/${moduleId}.dsp`;
  const outPath = `${paths.moduleDir}/dsp/${moduleId}_faust.c`;

  if (!(await exists(dspPath))) continue;
  any++;

  if (!hasFaust()) {
    console.error(
      `[${moduleId}] ${dspPath} exists but \`faust\` is not on $PATH. ` +
        `Install Faust (e.g. \`brew install faust\`) and re-run \`mise run gen-faust\`.`
    );
    if (mode === "check") {
      drift++;
      continue;
    }
    process.exit(1);
  }

  const cn = `${moduleId}_faust`;
  const tmpDir = await mkdtemp(join(tmpdir(), "moveforge-faust-"));
  const tmpOut = join(tmpDir, `${moduleId}_faust.c`);
  const result = spawnSync(
    "faust",
    ["-lang", "c", "-cn", cn, "-a", ARCH_FILE, dspPath, "-o", tmpOut],
    { encoding: "utf8" }
  );
  if (result.status !== 0) {
    console.error(`[${moduleId}] faust failed:\n${result.stderr}`);
    await rm(tmpDir, { recursive: true, force: true });
    process.exit(result.status ?? 1);
  }
  const body = await readFile(tmpOut, "utf8");
  await rm(tmpDir, { recursive: true, force: true });
  const header =
    `/* GENERATED by scripts/gen-faust.ts from ${moduleId}.dsp via Faust */\n` +
    `/* Regenerate with: mise run gen-faust (or: pnpm run gen-faust) */\n\n`;
  const generated = header + body;
  const existing = await readFile(outPath, "utf8").catch(() => "");

  if (mode === "check") {
    if (generated !== existing) {
      console.error(`[${moduleId}] ${outPath} is stale — run \`mise run gen-faust\``);
      drift++;
    }
    continue;
  }

  if (existing === generated) {
    console.log(`[${moduleId}] ${outPath} unchanged`);
    continue;
  }
  await writeFile(outPath, generated);
  console.log(`[${moduleId}] wrote ${outPath}`);
}

if (any === 0) {
  console.log("No .dsp sources found — nothing to do.");
}

if (mode === "check" && drift > 0) {
  process.exit(1);
}

async function exists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

function hasFaust(): boolean {
  const r = spawnSync("faust", ["--version"], { stdio: "ignore" });
  return r.status === 0;
}
