import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { modulePaths, selectedModuleIds } from "./lib/modules.ts";

type Param = {
  default: number;
  key: string;
  max: number;
  min: number;
  name?: string;
  step?: number;
  type: string;
};

type ModuleJson = {
  capabilities?: {
    ui_hierarchy?: {
      levels?: {
        root?: {
          params?: Param[];
        };
      };
    };
  };
  id: string;
};

export type GenerateOptions = {
  /** Module ids to process. Defaults to MODULE_ID (or all modules) via selectedModuleIds(). */
  moduleIds?: string[];
  /** "write" emits the .gen.inc; "check" only reports drift. Defaults to "write". */
  mode?: "check" | "write";
};

/**
 * Generate (or check) each module's <module>_params.gen.inc from module.json.
 * Returns the number of modules whose generated output is stale (0 when in sync).
 */
export async function generate(options: GenerateOptions = {}): Promise<number> {
  const mode = options.mode ?? "write";
  const moduleIds = options.moduleIds ?? (await selectedModuleIds());

  let drift = 0;
  for (const moduleId of moduleIds) {
    const paths = modulePaths(moduleId);
    const moduleJson = JSON.parse(await readFile(paths.moduleJson, "utf8")) as ModuleJson;
    const params = moduleJson.capabilities?.ui_hierarchy?.levels?.root?.params;
    if (!params) {
      console.warn(`[${moduleId}] no capabilities.ui_hierarchy.levels.root.params — skipping`);
      continue;
    }

    const generated = renderInc(moduleId, params);
    const existing = await readFile(paths.paramsGenInc, "utf8").catch(() => "");

    if (mode === "check") {
      if (generated !== existing) {
        console.error(`[${moduleId}] ${paths.paramsGenInc} is stale — run \`mise run gen-params\``);
        drift++;
      }
      continue;
    }

    if (existing === generated) {
      console.log(`[${moduleId}] ${paths.paramsGenInc} unchanged`);
      continue;
    }
    await writeFile(paths.paramsGenInc, generated);
    console.log(`[${moduleId}] wrote ${paths.paramsGenInc} (${params.length} param${params.length === 1 ? "" : "s"})`);
  }

  return drift;
}

function renderInc(moduleId: string, params: Param[]): string {
  const upper = moduleId.toUpperCase();
  const coreT = `${moduleId}_core_t`;
  const guard = `${upper}_PARAMS_GEN_INC`;

  const enumEntries = params.map((p, i) => `    ${enumName(upper, p.key)} = ${i}`).join(",\n");

  const idLookup = params
    .map((p) => `    if (strcmp(key, "${p.key}") == 0) return ${enumName(upper, p.key)};`)
    .join("\n");

  const setCases = params
    .map(
      (p) =>
        `        case ${enumName(upper, p.key)}: s->${p.key} = ${moduleId}_params_clampf_(value, ${cf(p.min)}, ${cf(p.max)}); break;`
    )
    .join("\n");

  const getCases = params
    .map((p) => `        case ${enumName(upper, p.key)}: return s->${p.key};`)
    .join("\n");

  const defaults = params.map((p) => `    s->${p.key} = ${cf(p.default)};`).join("\n");

  return `/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

#ifndef ${guard}
#define ${guard}

enum {
${enumEntries}
};

static inline float ${moduleId}_params_clampf_(float x, float lo, float hi) {
    return x < lo ? lo : (x > hi ? hi : x);
}

int ${moduleId}_param_id(const char *key) {
    if (!key) return -1;
${idLookup}
    return -1;
}

void ${moduleId}_set_param(${coreT} *s, int param_id, float value) {
    if (!s) return;
    switch (param_id) {
${setCases}
        default: break;
    }
}

float ${moduleId}_get_param(const ${coreT} *s, int param_id) {
    if (!s) return 0.0f;
    switch (param_id) {
${getCases}
        default: return 0.0f;
    }
}

void ${moduleId}_apply_defaults(${coreT} *s) {
    if (!s) return;
${defaults}
}

#endif
`;
}

function enumName(upper: string, key: string): string {
  return `${upper}_PARAM_${key.toUpperCase()}`;
}

function cf(value: number): string {
  if (!Number.isFinite(value)) throw new Error(`non-finite param value: ${value}`);
  const s = Number(value.toPrecision(9)).toString();
  return s.includes(".") || s.includes("e") || s.includes("E") ? `${s}f` : `${s}.0f`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2] === "--check" ? "check" : "write";
  const drift = await generate({ mode });
  if (mode === "check" && drift > 0) process.exit(1);
}
