#!/usr/bin/env node
/**
 * Generate build/{host,move,wasm}.ninja from the module graph.
 *
 * This replaces the compile half of build.sh, build-host.sh, build-wasm.sh,
 * test.sh and render-demo.sh. Those scripts each resolved the module list by
 * spawning `node scripts/module-target.ts` four to six times *per module*, then
 * assembled a `cc` line by hand and ran it unconditionally. Everything they
 * looked up already lives in scripts/lib/modules.ts, so here it is an import.
 *
 * What the move to ninja actually buys, beyond one language:
 *
 *   - Header dependencies come from the compiler (-MMD), not from a list a human
 *     maintains. build-wasm.sh carried SHARED_DEPS_SG/FX/MIDI_FX arrays whose own
 *     comment noted that an omission is a *correctness* bug: the build prints
 *     "cached", the browser keeps the stale .wasm, and a newly added parameter's
 *     <id>_param_id() silently returns -1. That class of bug is now impossible.
 *   - test.sh, build-host.sh and render-demo.sh had no staleness checking at all,
 *     so `check` recompiled every module's tests, sanitizer variants, render
 *     binary and host .so from scratch, serially, on every run.
 *
 * Objects are per-variant (see lib/toolchains.ts) because variants differ in
 * flags; within a variant they are shared, which is why the core object compiled
 * for test_<id>_core is reused by test_<id>_plugin.
 *
 * Regenerate with: mise run gen-ninja
 */
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { NinjaWriter } from "./lib/ninja.ts";
import { allModuleTargets, fileExists, type ModuleBuildTarget } from "./lib/modules.ts";
import {
  CROSS_PREFIX,
  HOST_LIB_VARIANT,
  MF_EXPORTS,
  MOVE_VARIANT,
  RENDER_VARIANT,
  SCH_EXPORTS,
  TEST_SAN_VARIANT,
  TEST_VARIANT,
  WASM_VARIANT,
  wasmLinkFlags,
  type Variant
} from "./lib/toolchains.ts";

/**
 * Module-independent tests. The shared DSP blocks (src/modules/_shared) and the
 * render harnesses' shared argument handling (tools/render_*.h) do not vary per
 * module, so they are built and run once rather than nine times.
 */
const SHARED_TESTS = ["tests/test_mf_dsp.c", "tests/test_render_harness.c"];

const GENERATED_HEADER = `Generated by scripts/gen-ninja.ts — do not edit.
Regenerate with: mise run gen-ninja`;

/**
 * Write build/{host,move,wasm}.ninja. Importable, so the build entry points call
 * it directly instead of paying for a second Node process to do it.
 */
export async function generateNinjaFiles(): Promise<string[]> {
  const modules = await allModuleTargets();
  await mkdir("build", { recursive: true });

  return [
    await writeNinja("build/host.ninja", await hostNinja(modules)),
    await writeNinja("build/move.ninja", moveNinja(modules)),
    await writeNinja("build/wasm.ninja", wasmNinja(modules))
  ];
}

async function main(): Promise<void> {
  for (const path of await generateNinjaFiles()) console.log(`wrote ${path}`);
}

async function writeNinja(path: string, writer: NinjaWriter): Promise<string> {
  await writeFile(path, writer.toString());
  return path;
}

/**
 * Where a target's headers come from, and the object directory that goes with it.
 *
 * `-Isrc` is what resolves the `host/plugin_api_v1.h` style includes in the
 * wrappers; the module's own dsp/ directory is what resolves its generated
 * *.gen.h and *.gen.inc. `scope` keys the object directory, because the same
 * source compiled against a different module's dsp/ is a different object.
 */
type IncludeScope = { includes: string[]; scope: string };

function includesFor(module: ModuleBuildTarget): IncludeScope {
  return {
    includes: ["-Isrc", `-I${module.paths.moduleDir}/dsp`],
    scope: module.id
  };
}

const SHARED_SCOPE: IncludeScope = { includes: ["-Isrc"], scope: "_shared" };

/**
 * The compile+link rule pair for one toolchain.
 *
 * Compiling to .o first is not gold-plating: `-MF` cannot emit a depfile for
 * several translation units at once, so the one-shot `cc a.c b.c -o prog` form
 * the bash used is incompatible with dependency tracking. Splitting the steps is
 * what makes -MMD usable, and it means editing one module's core relinks rather
 * than recompiles its siblings.
 */
function emitRules(ninja: NinjaWriter, cc: string): void {
  ninja.variable("cc", cc);
  ninja.comment(
    "deps = gcc makes ninja read the compiler's -MMD output, so a header edit\n" +
      "rebuilds exactly the objects that included it."
  );
  ninja.rule("compile", {
    command: "$cc -MMD -MF $out.d $cflags $includes -c $in -o $out",
    depfile: "$out.d",
    deps: "gcc",
    description: "CC $out"
  });
  ninja.rule("link", {
    command: "$cc $ldflags_pre $in -o $out $ldflags",
    description: "LINK $out"
  });
}

/**
 * One target: compile every source into the variant's object dir, then link.
 * Returns the linked output path.
 */
function emitTarget(
  ninja: NinjaWriter,
  variant: Variant,
  output: string,
  sources: string[],
  scope: IncludeScope,
  /** Replaces the variant's link flags. The wasm build needs a per-module export list. */
  ldflags?: string[]
): string {
  const objects = sources.map((source) => objectPath(variant, source, scope));
  for (const [index, source] of sources.entries()) {
    ninja.build({
      outputs: [objects[index]],
      rule: "compile",
      inputs: [source],
      variables: { cflags: variant.cflags.join(" "), includes: scope.includes.join(" ") }
    });
  }
  ninja.build({
    outputs: [output],
    rule: "link",
    inputs: objects,
    variables: {
      ldflags_pre: variant.shared ? "-shared" : "",
      ldflags: (ldflags ?? variant.ldflags).join(" ")
    }
  });
  return output;
}

/**
 * Object path for a source under a variant.
 *
 * The scope is part of the key, not just the variant: a shared source such as a
 * wasm glue file is compiled once per module, because each module's dsp/
 * directory supplies a different set of generated headers. Keying on the variant
 * alone would silently reuse the first module's object for every module.
 */
function objectPath(variant: Variant, source: string, scope: IncludeScope): string {
  const flat = source.replace(/[^A-Za-z0-9]+/g, "_");
  return `build/obj/${variant.id}/${scope.scope}/${flat}.o`;
}

/** Tests are only interesting when they run, so the run is an edge too. */
function emitTestRun(ninja: NinjaWriter, binary: string, label: string, quiet = false): string {
  const stamp = `build/stamp/${label}.ok`;
  ninja.build({
    outputs: [stamp],
    rule: quiet ? "run_test_quiet" : "run_test",
    inputs: [binary],
    variables: { label }
  });
  return stamp;
}

async function hostNinja(modules: ModuleBuildTarget[]): Promise<NinjaWriter> {
  const ninja = new NinjaWriter(
    `${GENERATED_HEADER}\n\nHost toolchain: C tests (plain and sanitized), offline render\nharnesses, and the host-only shared libraries. Runs on this machine.`,
    "build/.ninja-host"
  );
  emitRules(ninja, process.env.CC || "cc");

  ninja.comment(
    "Running a test is a build edge with a stamp file, so a test whose inputs are\n" +
      "unchanged does not re-run. To force every test to run again:\n" +
      "    rm -rf build/stamp && mise run test-c\n" +
      "(there is no --force flag here: mise passes unrecognised arguments through\n" +
      "to ninja, which rejects them, so `mise run test-c --force` simply fails.)\n" +
      "\n" +
      "The sanitizer pass discards stdout: it re-runs the same assertions as the\n" +
      "plain pass, and what is wanted from it is ASan/UBSan's own report on stderr."
  );
  ninja.rule("run_test", {
    command: "$in && touch $out",
    description: "TEST $label"
  });
  ninja.rule("run_test_quiet", {
    command: "$in > /dev/null && touch $out",
    description: "TEST $label"
  });

  const testStamps: string[] = [];
  const sanStamps: string[] = [];
  const renderBins: string[] = [];
  const hostLibs: string[] = [];

  ninja.comment("Module-independent tests: shared DSP blocks and render-harness argument handling.");
  for (const source of SHARED_TESTS) {
    if (!(await fileExists(source))) continue;
    const name = basename(source);
    const binary = emitTarget(ninja, TEST_VARIANT, `build/${name}`, [source], SHARED_SCOPE);
    testStamps.push(emitTestRun(ninja, binary, name));
    const sanBinary = emitTarget(ninja, TEST_SAN_VARIANT, `build/${name}_san`, [source], SHARED_SCOPE);
    sanStamps.push(emitTestRun(ninja, sanBinary, `${name}_san`, true));
  }

  for (const module of modules) {
    const scope = includesFor(module);
    const { coreImpl, id, paths } = module;
    ninja.comment(`--- ${id} (${module.componentType}, ${module.dspAuthoring}) ---`);

    for (const variant of [TEST_VARIANT, TEST_SAN_VARIANT]) {
      const sanitized = variant === TEST_SAN_VARIANT;
      const suffix = sanitized ? "_san" : "";
      const stamps = sanitized ? sanStamps : testStamps;

      if (await fileExists(paths.testCoreC)) {
        const binary = emitTarget(
          ninja,
          variant,
          `build/test_${id}_core${suffix}`,
          [paths.testCoreC, coreImpl],
          scope
        );
        stamps.push(emitTestRun(ninja, binary, `test_${id}_core${suffix}`, sanitized));
      }
      if (await fileExists(paths.testPluginC)) {
        const binary = emitTarget(
          ninja,
          variant,
          `build/test_${id}_plugin${suffix}`,
          [paths.testPluginC, paths.wrapperC, coreImpl],
          scope
        );
        stamps.push(emitTestRun(ninja, binary, `test_${id}_plugin${suffix}`, sanitized));
      }
    }

    const harness = renderHarnessFor(module);
    if (harness) {
      renderBins.push(
        emitTarget(
          ninja,
          RENDER_VARIANT,
          module.renderBin.replace(/^\.\//, ""),
          [harness, paths.wrapperC, coreImpl],
          scope
        )
      );
    }

    hostLibs.push(
      emitTarget(
        ninja,
        HOST_LIB_VARIANT,
        `build-host/${id}-dsp.so`,
        [paths.wrapperC, coreImpl],
        scope
      )
    );
  }

  ninja.phony("tests", testStamps);
  ninja.phony("tests-san", sanStamps);
  ninja.phony("renders", renderBins);
  ninja.phony("hostlib", hostLibs);
  ninja.default_(["tests"]);
  return ninja;
}

/** The offline harness for a module's kind, or null if it has none. */
function renderHarnessFor(module: ModuleBuildTarget): string | null {
  if (module.renderKind === "sound_generator") return "tools/render_wav.c";
  if (module.renderKind === "audio_fx") return "tools/render_fx.c";
  if (module.renderKind === "midi_fx") return "tools/trace_midi_fx.c";
  return null;
}

function moveNinja(modules: ModuleBuildTarget[]): NinjaWriter {
  const ninja = new NinjaWriter(
    `${GENERATED_HEADER}\n\naarch64 device build. Runs inside the cross-compile container\n(scripts/Dockerfile) via scripts/build-move.ts, so ${CROSS_PREFIX}gcc\nand these paths are resolved container-side.`,
    "build/.ninja-move"
  );
  emitRules(ninja, `${CROSS_PREFIX}gcc`);

  const outputs = modules.map((module) =>
    emitTarget(
      ninja,
      MOVE_VARIANT,
      `build/${module.id}-dsp.so`,
      [module.paths.wrapperC, module.coreImpl],
      includesFor(module)
    )
  );
  ninja.phony("all", outputs);
  ninja.default_(outputs);
  return ninja;
}

function wasmNinja(modules: ModuleBuildTarget[]): NinjaWriter {
  const ninja = new NinjaWriter(
    `${GENERATED_HEADER}\n\nBrowser build. Runs inside the emsdk container via\nscripts/build-wasm.ts.`,
    "build/.ninja-wasm"
  );
  emitRules(ninja, "emcc");

  const outputs: string[] = [];
  for (const module of modules) {
    if (!module.wasmGlue) {
      ninja.comment(`${module.id}: no WASM path for component_type=${module.componentType}`);
      continue;
    }
    outputs.push(
      emitTarget(
        ninja,
        WASM_VARIANT,
        `web/wasm/${module.id}.wasm`,
        [module.paths.wrapperC, module.coreImpl, module.wasmGlue],
        includesFor(module),
        wasmLinkFlags(module.componentType === "midi_fx" ? MF_EXPORTS : SCH_EXPORTS)
      )
    );
  }
  ninja.phony("all", outputs);
  ninja.default_(outputs);
  return ninja;
}

function basename(path: string): string {
  return path.replace(/^.*\//, "").replace(/\.c$/, "");
}

// Last, not first: the module-level `const`s above are in their temporal dead
// zone until this point, so invoking main() at the top of the file would fail on
// the first one it touched.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await main();
}
