/*
 * Generate <module>/ui_chain.js from module.json.
 *
 * A Schwung module must ship a real ui_chain.js to be openable (wheel press)
 * in a chain slot: the host loads ui_chain.js and renders the detail screen
 * only if it sets globalThis.chain_ui with a tick() that draws. An empty/no-op
 * chain_ui (the old template stub) draws nothing — the slot appears dead.
 *
 * This emits a scrollable parameter editor with optional 8-encoder banks:
 * the jog wheel scrolls/selects/edits one focused row, and Knob 1..8 adjust
 * the active bank declared by module.json's root.knobs order. Param metadata
 * is taken from module.json so it never drifts.
 *
 * GENERATED FILE — do not hand-edit <module>/ui_chain.js; edit module.json and
 * re-run `mise run gen-ui-chain`.
 */
import { readFile, writeFile, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { modulePaths, selectedModuleIds } from "./lib/modules.ts";

type Param = { key: string; name?: string; min: number; max: number; default: number; step?: number };
type ModuleJson = {
  name?: string;
  ui_chain?: string;
  capabilities?: {
    component_type?: string;
    ui_hierarchy?: { levels?: { root?: { params?: Param[]; knobs?: string[] } } };
  };
};

const EDITABLE_TYPES = new Set(["sound_generator", "audio_fx", "midi_fx"]);
const ENCODER_COUNT = 8; // Move parameter encoders, CC 71-78

/* Knob detents across a param's range. Respect module.json step when it gives a
 * reasonable detent count (e.g. integer selectors like trail's "sync"),
 * otherwise spread ~50 detents across the range for a good knob feel. */
function editStep(p: Param): number {
  const range = p.max - p.min;
  if (range <= 0) return 0.01;
  const declared = p.step ?? 0;
  if (declared > 0 && range / declared <= 100) return declared;
  return range / 50;
}

function decimalsFor(step: number): number {
  if (step >= 1) return 0;
  if (step >= 0.1) return 1;
  return 2;
}

function renderUiChain(id: string, json: ModuleJson, params: Param[]): string {
  const name = json.name ?? id;
  const requestedKnobs = json.capabilities?.ui_hierarchy?.levels?.root?.knobs ?? [];
  const paramIndexByKey = new Map(params.map((p, i) => [p.key, i]));
  const knobIndexes = (requestedKnobs.length > 0 ? requestedKnobs : params.map((p) => p.key))
    .map((key) => paramIndexByKey.get(key))
    .filter((index): index is number => index !== undefined);
  const rows = params
    .map((p) => {
      const step = editStep(p);
      const dec = decimalsFor(step);
      const label = p.name ?? p.key;
      return `    { key: ${JSON.stringify(p.key)}, name: ${JSON.stringify(label)}, ` +
        `min: ${p.min}, max: ${p.max}, step: ${round(step)}, dec: ${dec}, def: ${p.default} }`;
    })
    .join(",\n");
  const knobRows = knobIndexes.map((index) => `    ${index}`).join(",\n");

  return `/*
 * ${name} Chain UI — GENERATED by scripts/gen-ui-chain.ts from module.json.
 * Do not edit by hand: change module.json and re-run \`mise run gen-ui-chain\`.
 *
 * Scrollable parameter editor shown when this module is opened (wheel press)
 * in a chain slot. Knob 1..${ENCODER_COUNT} adjust the active encoder bank
 * declared by module.json's root.knobs order, and the jog wheel
 * scrolls/selects/edits focused rows. Press the Encoder Bank row to switch banks.
 * Sets globalThis.chain_ui.
 */

import {
    MoveMainButton, MoveMainKnob,
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4,
    MoveKnob5, MoveKnob6, MoveKnob7, MoveKnob8
} from '/data/UserData/schwung/shared/constants.mjs';

import { decodeDelta } from '/data/UserData/schwung/shared/input_filter.mjs';

import {
    drawMenuFooter as drawFooter,
    drawMenuHeader as drawHeader,
    drawMenuList,
    FOOTER_RULE_Y,
    LIST_TOP_Y
} from '/data/UserData/schwung/shared/menu_layout.mjs';

const ENCODER_COUNT = ${ENCODER_COUNT};
const KNOBS = [
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4,
    MoveKnob5, MoveKnob6, MoveKnob7, MoveKnob8
];

const PARAMS = [
${rows}
];

const KNOB_PARAM_INDEXES = [
${knobRows}
];

let selectedIndex = 0;
let paramValues = PARAMS.map((p) => p.def);
let presetCount = 0;
let presetIndex = 0;
let presetName = "";
let mode = "params";
let editMode = false;
let encoderPage = 0;
let lastEncoderLabel = "";
let needsRedraw = true;

function clampSelected(v) {
    return Math.max(0, Math.min(Math.max(0, displayItemCount() - 1), v));
}

function hasEncoderBankRow() {
    return pageCount() > 1;
}

function displayItemCount() {
    return hasEncoderBankRow() ? (1 + bankParamIndexes().length) : PARAMS.length;
}

function selectedParamIndex() {
    if (hasEncoderBankRow()) {
        if (selectedIndex === 0) return -1;
        return bankParamIndexes()[selectedIndex - 1] ?? -1;
    }
    return selectedIndex;
}

function displayIndexForParam(paramIndex) {
    if (!hasEncoderBankRow()) return paramIndex;
    const slot = bankParamIndexes().indexOf(paramIndex);
    if (slot >= 0) return slot + 1;
    return 0;
}

function displayItems() {
    if (!hasEncoderBankRow()) return PARAMS;
    return [{ bank: true, name: "Encoder Bank" }, ...bankParamIndexes().map((index) => PARAMS[index])];
}

function isBankRow(index) {
    return hasEncoderBankRow() && index === 0;
}

function pageCount() {
    return Math.max(1, Math.ceil(Math.max(1, KNOB_PARAM_INDEXES.length) / ENCODER_COUNT));
}

function clampPage(v) {
    return Math.max(0, Math.min(pageCount() - 1, v));
}

function wrapPage(v) {
    const count = pageCount();
    return ((v % count) + count) % count;
}

function pageStart() {
    return encoderPage * ENCODER_COUNT;
}

function bankParamIndexes() {
    const start = pageStart();
    return KNOB_PARAM_INDEXES.slice(start, start + ENCODER_COUNT).filter((index) => index !== undefined && index < PARAMS.length);
}

function pageLabel() {
    return String(encoderPage + 1) + "/" + String(pageCount());
}

function selectIndex(index) {
    selectedIndex = clampSelected(index);
    editMode = false;
    lastEncoderLabel = "";
    needsRedraw = true;
}

function setEncoderPage(page) {
    const next = clampPage(page);
    if (next === encoderPage) return;
    encoderPage = next;
    selectedIndex = 0;
    lastEncoderLabel = "";
    needsRedraw = true;
}

function fetchParams() {
    for (let i = 0; i < PARAMS.length; i++) {
        const val = host_module_get_param(PARAMS[i].key);
        if (val !== null && val !== undefined) {
            const f = parseFloat(val);
            if (!isNaN(f)) paramValues[i] = f;
        }
    }
}

function fetchPreset() {
    const count = host_module_get_param("preset_count");
    const parsedCount = count !== null && count !== undefined ? parseInt(count) : 0;
    presetCount = isNaN(parsedCount) ? 0 : Math.max(0, parsedCount);

    const preset = host_module_get_param("preset");
    const parsedPreset = preset !== null && preset !== undefined ? parseInt(preset) : 0;
    presetIndex = isNaN(parsedPreset) ? 0 : Math.max(0, Math.min(Math.max(0, presetCount - 1), parsedPreset));

    presetName = host_module_get_param("preset_name") || "";
}

function setParam(index, value) {
    const param = PARAMS[index];
    value = Math.max(param.min, Math.min(param.max, value));
    paramValues[index] = value;
    host_module_set_param(param.key, value.toFixed(2));
}

function adjustParam(index, delta) {
    setParam(index, paramValues[index] + delta * PARAMS[index].step);
    needsRedraw = true;
}

function changePreset(delta) {
    if (presetCount <= 0) return;
    let next = presetIndex + delta;
    if (next < 0) next = presetCount - 1;
    if (next >= presetCount) next = 0;
    presetIndex = next;
    host_module_set_param("preset", String(presetIndex));
    fetchPreset();
    fetchParams();
    needsRedraw = true;
}

function toggleMode() {
    if (presetCount <= 0) return;
    mode = mode === "preset" ? "params" : "preset";
    editMode = false;
    needsRedraw = true;
}

function toggleEncoderPage() {
    if (mode !== "params" || pageCount() <= 1) return;
    setEncoderPage(wrapPage(encoderPage + 1));
}

function toggleEditMode() {
    if (mode !== "params" || PARAMS.length === 0) return;
    if (isBankRow(selectedIndex)) {
        toggleEncoderPage();
        return;
    }
    editMode = !editMode;
    needsRedraw = true;
}

function drawCentered(y, text) {
    const s = String(text || "");
    const x = Math.max(0, Math.floor((128 - s.length * 5) / 2));
    print(x, y, s, 1);
}

function drawPresetUI() {
    clear_screen();
    drawHeader(${JSON.stringify(name)});

    fetchPreset();
    if (presetCount > 0) {
        drawCentered(24, String(presetIndex + 1) + " / " + String(presetCount));
        drawCentered(36, presetName || "Preset " + String(presetIndex + 1));
        print(4, 32, "<", 1);
        print(118, 32, ">", 1);
        drawFooter({left: "Back: done", right: "Click: params"});
    } else {
        drawCentered(32, "No presets");
        drawFooter("Back: done");
    }

    needsRedraw = false;
}

function drawUI() {
    if (mode === "preset") {
        drawPresetUI();
        return;
    }

    clear_screen();
    drawHeader(${JSON.stringify(name)} + " " + pageLabel());

    drawMenuList({
        items: displayItems(),
        selectedIndex,
        listArea: { topY: LIST_TOP_Y, bottomY: FOOTER_RULE_Y },
        getLabel: (p) => p.name,
        getValue: (p, i) => {
            if (p.bank) return pageLabel();
            const paramIndex = hasEncoderBankRow() ? bankParamIndexes()[i - 1] : i;
            return paramValues[paramIndex].toFixed(PARAMS[paramIndex].dec);
        },
        valueAlignRight: true,
        editMode,
        keepOffLastRow: false,
        scrollSelectedValue: true,
        prioritizeSelectedValue: true,
        selectedMinLabelChars: 6
    });
    drawFooter(isBankRow(selectedIndex)
        ? {left: "Click: bank", right: lastEncoderLabel || "Knobs: adjust"}
        : (editMode ? {left: "Click: done", right: "Jog: adjust"} : {left: "Click: edit", right: lastEncoderLabel || "Knobs: adjust"}));

    needsRedraw = false;
}

function init() {
    fetchParams();
    fetchPreset();
    mode = presetCount > 0 ? "preset" : "params";
    editMode = false;
    selectedIndex = 0;
    encoderPage = 0;
    lastEncoderLabel = "";
    needsRedraw = true;
}

function tick() {
    if (needsRedraw) drawUI();
}

function onMidiMessageInternal(data) {
    const status = data[0];
    const d1 = data[1];
    const d2 = data[2];
    if ((status & 0xF0) !== 0xB0) return;

    if (d1 === MoveMainButton && d2 > 0) {
        if (mode === "params") toggleEditMode();
        else toggleMode();
        return;
    }

    /* Jog wheel scrolls/selects, or adjusts the selected param in edit mode. */
    if (d1 === MoveMainKnob) {
        const delta = decodeDelta(d2);
        if (mode === "preset") {
            if (delta !== 0) changePreset(delta);
            return;
        }
        if (editMode) {
            const paramIndex = selectedParamIndex();
            if (delta !== 0 && paramIndex >= 0) adjustParam(paramIndex, delta);
            return;
        }
        if (delta !== 0) {
            const next = clampSelected(selectedIndex + delta);
            if (next !== selectedIndex) {
                selectIndex(next);
            }
        }
        return;
    }

    /* The 8 parameter encoders adjust the active module.json knob bank. */
    const start = pageStart();
    for (let k = 0; k < ENCODER_COUNT; k++) {
        if (d1 === KNOBS[k]) {
            const knobIndex = start + k;
            const paramIndex = KNOB_PARAM_INDEXES[knobIndex];
            const delta = decodeDelta(d2);
            if (delta !== 0 && paramIndex !== undefined && paramIndex < PARAMS.length) {
                lastEncoderLabel = "K" + String(k + 1) + " " + PARAMS[paramIndex].name;
                if (!isBankRow(selectedIndex)) {
                    selectedIndex = displayIndexForParam(paramIndex);
                }
                editMode = false;
                adjustParam(paramIndex, delta);
            } else if (delta !== 0) {
                lastEncoderLabel = "K" + String(k + 1) + " --";
                needsRedraw = true;
            }
            return;
        }
    }
}

globalThis.chain_ui = {
    init,
    tick,
    onMidiMessageInternal
};
`;
}

function round(n: number): number {
  return Math.round(n * 1e6) / 1e6;
}

async function exists(p: string): Promise<boolean> {
  try { await stat(p); return true; } catch { return false; }
}

export type GenerateOptions = {
  /** Module ids to process. Defaults to MODULE_ID (or all modules) via selectedModuleIds(). */
  moduleIds?: string[];
  /** "write" emits ui_chain.js; "check" only reports drift. Defaults to "write". */
  mode?: "check" | "write";
};

/**
 * Generate (or check) each editable module's ui_chain.js from module.json.
 * Modules without editable params (e.g. settings/tool modules) are skipped.
 * Returns the number of modules whose generated output is stale (0 when in sync).
 */
export async function generate(options: GenerateOptions = {}): Promise<number> {
  const mode = options.mode ?? "write";
  const moduleIds = options.moduleIds ?? (await selectedModuleIds());

  let drift = 0;
  for (const id of moduleIds) {
    const paths = modulePaths(id);
    const json: ModuleJson = JSON.parse(await readFile(paths.moduleJson, "utf8"));
    const ct = json.capabilities?.component_type;
    const params = json.capabilities?.ui_hierarchy?.levels?.root?.params ?? [];

    const outPath = `${paths.moduleDir}/ui_chain.js`;

    if (!ct || !EDITABLE_TYPES.has(ct) || params.length === 0) {
      continue; // nothing to render (e.g. settings/tool modules)
    }

    const generated = renderUiChain(id, json, params);
    const existing = (await exists(outPath)) ? await readFile(outPath, "utf8") : "";

    if (mode === "check") {
      if (generated !== existing) {
        console.error(`[${id}] ${outPath} is stale — run \`mise run gen-ui-chain\``);
        drift++;
      }
      continue;
    }

    if (existing === generated) {
      console.log(`[${id}] ${outPath} unchanged`);
    } else {
      await writeFile(outPath, generated);
      console.log(`[${id}] wrote ${outPath} (${params.length} params)`);
    }
  }

  return drift;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2] === "--check" ? "check" : "write";
  const drift = await generate({ mode });
  if (mode === "check" && drift > 0) process.exit(1);
}
