/*
 * Generate <module>/ui_chain.js from module.json.
 *
 * A Schwung module must ship a real ui_chain.js to be openable (wheel press)
 * in a chain slot: the host loads ui_chain.js and renders the detail screen
 * only if it sets globalThis.chain_ui with a tick() that draws. An empty/no-op
 * chain_ui (the old template stub) draws nothing — the slot appears dead.
 *
 * This emits a scrollable parameter editor modeled on the stock freeverb
 * ui_chain.js: the top knobs (Knob 1..6) adjust the visible params, the jog
 * wheel scrolls when there are more params than fit on screen. Param metadata
 * is taken from module.json so it never drifts.
 *
 * GENERATED FILE — do not hand-edit <module>/ui_chain.js; edit module.json and
 * re-run `mise run gen-ui-chain`.
 */
import { readFile, writeFile, stat } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { modulePaths, selectedModuleIds } from "./lib/modules.ts";

type Param = { key: string; name?: string; min: number; max: number; default: number; step?: number };
type ModuleJson = {
  name?: string;
  ui_chain?: string;
  capabilities?: {
    component_type?: string;
    ui_hierarchy?: { levels?: { root?: { params?: Param[] } } };
  };
};

const EDITABLE_TYPES = new Set(["sound_generator", "audio_fx", "midi_fx"]);
const VISIBLE = 5; // rows on screen / knobs mapped at once, leaving footer space

/* Knob detents across a param's range. Respect module.json step when it gives a
 * reasonable detent count (e.g. integer selectors like trail's "sync"),
 * otherwise spread ~50 detents across the range for a good knob feel. */
function editStep(p: Param): number {
  const range = p.max - p.min;
  if (range <= 0) return 0.01;
  const declared = p.step ?? 0;
  if (declared > 0 && range / declared <= 100) return declared;
  return range / 50;
}

function decimalsFor(step: number): number {
  if (step >= 1) return 0;
  if (step >= 0.1) return 1;
  return 2;
}

function renderUiChain(id: string, json: ModuleJson, params: Param[]): string {
  const name = json.name ?? id;
  const rows = params
    .map((p) => {
      const step = editStep(p);
      const dec = decimalsFor(step);
      const label = p.name ?? p.key;
      return `    { key: ${JSON.stringify(p.key)}, name: ${JSON.stringify(label)}, ` +
        `min: ${p.min}, max: ${p.max}, step: ${round(step)}, dec: ${dec}, def: ${p.default} }`;
    })
    .join(",\n");

  return `/*
 * ${name} Chain UI — GENERATED by scripts/gen-ui-chain.ts from module.json.
 * Do not edit by hand: change module.json and re-run \`mise run gen-ui-chain\`.
 *
 * Scrollable parameter editor shown when this module is opened (wheel press)
 * in a chain slot. Top knobs (Knob 1..${VISIBLE}) adjust the visible params; the
 * jog wheel scrolls when there are more than ${VISIBLE}. Sets globalThis.chain_ui.
 */

import {
    MoveMainButton, MoveMainKnob,
    MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4, MoveKnob5, MoveKnob6
} from '/data/UserData/schwung/shared/constants.mjs';

import { decodeDelta } from '/data/UserData/schwung/shared/input_filter.mjs';

import {
    drawMenuFooter as drawFooter,
    drawMenuHeader as drawHeader,
    drawMenuList,
    FOOTER_RULE_Y,
    LIST_TOP_Y
} from '/data/UserData/schwung/shared/menu_layout.mjs';

const KNOBS = [MoveKnob1, MoveKnob2, MoveKnob3, MoveKnob4, MoveKnob5, MoveKnob6];

const PARAMS = [
${rows}
];

let selectedIndex = 0;
let paramValues = PARAMS.map((p) => p.def);
let presetCount = 0;
let presetIndex = 0;
let presetName = "";
let mode = "params";
let editMode = false;
let needsRedraw = true;

function clampSelected(v) {
    return Math.max(0, Math.min(Math.max(0, PARAMS.length - 1), v));
}

function fetchParams() {
    for (let i = 0; i < PARAMS.length; i++) {
        const val = host_module_get_param(PARAMS[i].key);
        if (val !== null && val !== undefined) {
            const f = parseFloat(val);
            if (!isNaN(f)) paramValues[i] = f;
        }
    }
}

function fetchPreset() {
    const count = host_module_get_param("preset_count");
    const parsedCount = count !== null && count !== undefined ? parseInt(count) : 0;
    presetCount = isNaN(parsedCount) ? 0 : Math.max(0, parsedCount);

    const preset = host_module_get_param("preset");
    const parsedPreset = preset !== null && preset !== undefined ? parseInt(preset) : 0;
    presetIndex = isNaN(parsedPreset) ? 0 : Math.max(0, Math.min(Math.max(0, presetCount - 1), parsedPreset));

    presetName = host_module_get_param("preset_name") || "";
}

function setParam(index, value) {
    const param = PARAMS[index];
    value = Math.max(param.min, Math.min(param.max, value));
    paramValues[index] = value;
    host_module_set_param(param.key, value.toFixed(2));
}

function adjustParam(index, delta) {
    setParam(index, paramValues[index] + delta * PARAMS[index].step);
    needsRedraw = true;
}

function changePreset(delta) {
    if (presetCount <= 0) return;
    let next = presetIndex + delta;
    if (next < 0) next = presetCount - 1;
    if (next >= presetCount) next = 0;
    presetIndex = next;
    host_module_set_param("preset", String(presetIndex));
    fetchPreset();
    fetchParams();
    needsRedraw = true;
}

function toggleMode() {
    if (presetCount <= 0) return;
    mode = mode === "preset" ? "params" : "preset";
    editMode = false;
    needsRedraw = true;
}

function toggleEditMode() {
    if (mode !== "params" || PARAMS.length === 0) return;
    editMode = !editMode;
    needsRedraw = true;
}

function drawCentered(y, text) {
    const s = String(text || "");
    const x = Math.max(0, Math.floor((128 - s.length * 5) / 2));
    print(x, y, s, 1);
}

function drawPresetUI() {
    clear_screen();
    drawHeader(${JSON.stringify(name)});

    fetchPreset();
    if (presetCount > 0) {
        drawCentered(24, String(presetIndex + 1) + " / " + String(presetCount));
        drawCentered(36, presetName || "Preset " + String(presetIndex + 1));
        print(4, 32, "<", 1);
        print(118, 32, ">", 1);
        drawFooter({left: "Back: done", right: "Click: params"});
    } else {
        drawCentered(32, "No presets");
        drawFooter("Back: done");
    }

    needsRedraw = false;
}

function drawUI() {
    if (mode === "preset") {
        drawPresetUI();
        return;
    }

    clear_screen();
    drawHeader(${JSON.stringify(name)});

    drawMenuList({
        items: PARAMS,
        selectedIndex,
        listArea: { topY: LIST_TOP_Y, bottomY: FOOTER_RULE_Y },
        getLabel: (p) => p.name,
        getValue: (_p, i) => paramValues[i].toFixed(PARAMS[i].dec),
        valueAlignRight: true,
        editMode,
        keepOffLastRow: false,
        scrollSelectedValue: true,
        prioritizeSelectedValue: true,
        selectedMinLabelChars: 6
    });
    drawFooter(editMode ? {left: "Click: done", right: "Jog: adjust"} : {left: "Back: done", right: "Click: edit"});

    needsRedraw = false;
}

function init() {
    fetchParams();
    fetchPreset();
    mode = presetCount > 0 ? "preset" : "params";
    editMode = false;
    selectedIndex = 0;
    needsRedraw = true;
}

function tick() {
    if (needsRedraw) drawUI();
}

function onMidiMessageInternal(data) {
    const status = data[0];
    const d1 = data[1];
    const d2 = data[2];
    if ((status & 0xF0) !== 0xB0) return;

    if (d1 === MoveMainButton && d2 > 0) {
        if (mode === "params") toggleEditMode();
        else toggleMode();
        return;
    }

    /* Jog wheel scrolls the visible window. */
    if (d1 === MoveMainKnob) {
        const delta = decodeDelta(d2);
        if (mode === "preset") {
            if (delta !== 0) changePreset(delta);
            return;
        }
        if (editMode) {
            if (delta !== 0) adjustParam(selectedIndex, delta);
            return;
        }
        if (delta !== 0) {
            const next = clampSelected(selectedIndex + delta);
            if (next !== selectedIndex) {
                selectedIndex = next;
                needsRedraw = true;
            }
        }
        return;
    }

    /* Each visible row is adjusted by its corresponding top knob. */
    for (let k = 0; k < VISIBLE; k++) {
        if (d1 === KNOBS[k]) {
            const delta = decodeDelta(d2);
            if (delta !== 0 && k < PARAMS.length) adjustParam(k, delta);
            return;
        }
    }
}

globalThis.chain_ui = {
    init,
    tick,
    onMidiMessageInternal
};
`;
}

function round(n: number): number {
  return Math.round(n * 1e6) / 1e6;
}

async function exists(p: string): Promise<boolean> {
  try { await stat(p); return true; } catch { return false; }
}

export type GenerateOptions = {
  /** Module ids to process. Defaults to MODULE_ID (or all modules) via selectedModuleIds(). */
  moduleIds?: string[];
  /** "write" emits ui_chain.js; "check" only reports drift. Defaults to "write". */
  mode?: "check" | "write";
};

/**
 * Generate (or check) each editable module's ui_chain.js from module.json.
 * Modules without editable params (e.g. settings/tool modules) are skipped.
 * Returns the number of modules whose generated output is stale (0 when in sync).
 */
export async function generate(options: GenerateOptions = {}): Promise<number> {
  const mode = options.mode ?? "write";
  const moduleIds = options.moduleIds ?? (await selectedModuleIds());

  let drift = 0;
  for (const id of moduleIds) {
    const paths = modulePaths(id);
    const json: ModuleJson = JSON.parse(await readFile(paths.moduleJson, "utf8"));
    const ct = json.capabilities?.component_type;
    const params = json.capabilities?.ui_hierarchy?.levels?.root?.params ?? [];

    const outPath = `${paths.moduleDir}/ui_chain.js`;

    if (!ct || !EDITABLE_TYPES.has(ct) || params.length === 0) {
      continue; // nothing to render (e.g. settings/tool modules)
    }

    const generated = renderUiChain(id, json, params);
    const existing = (await exists(outPath)) ? await readFile(outPath, "utf8") : "";

    if (mode === "check") {
      if (generated !== existing) {
        console.error(`[${id}] ${outPath} is stale — run \`mise run gen-ui-chain\``);
        drift++;
      }
      continue;
    }

    if (existing === generated) {
      console.log(`[${id}] ${outPath} unchanged`);
    } else {
      await writeFile(outPath, generated);
      console.log(`[${id}] wrote ${outPath} (${params.length} params)`);
    }
  }

  return drift;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2] === "--check" ? "check" : "write";
  const drift = await generate({ mode });
  if (mode === "check" && drift > 0) process.exit(1);
}
