import { readFile, stat, mkdtemp, rm } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { modulePaths, selectedModuleIds } from "./lib/modules.ts";
import { type GenerateOptions, writeGeneratedFile } from "./lib/generated-files.ts";

const ARCH_FILE = "src/host/faust_module_arch.c.in";

/**
 * Generate (or check) each Faust module's <module>_faust.c from <module>.dsp.
 * Modules without a .dsp source are skipped. Returns the number of modules
 * whose generated output is stale or could not be regenerated (0 when in sync).
 *
 * In "write" mode a missing `faust` binary is fatal (process exits non-zero),
 * matching the prior CLI behavior.
 */
export async function generate(options: GenerateOptions = {}): Promise<number> {
  const mode = options.mode ?? "write";
  const moduleIds = options.moduleIds ?? (await selectedModuleIds());

  let drift = 0;
  let any = 0;

  for (const moduleId of moduleIds) {
    const paths = modulePaths(moduleId);
    const dspPath = `${paths.moduleDir}/dsp/${moduleId}.dsp`;
    const outPath = `${paths.moduleDir}/dsp/${moduleId}_faust.c`;

    if (!(await exists(dspPath))) continue;
    any++;

    /* Check mode is a *drift* check, and drift is only meaningful when the
     * local compiler is the one that produced the committed artifact.
     *
     * The generated C embeds its Faust version and its stdfaust.lib versions,
     * and the comparison is byte-exact, so a different Faust reports drift on
     * every Faust module without anyone having touched a .dsp — and the
     * "fix" (running gen-faust) would rewrite tens of KB of C with different
     * inlining and scheduling, silently changing the DSP output.
     *
     * So: skip with a warning when Faust is missing or is a different version,
     * and only byte-compare when the versions agree. This is also what makes
     * `mise run validate` runnable by a contributor touching only plain-C
     * modules, which README.md has always claimed. */
    if (mode === "check") {
      const local = faustVersion();
      const recorded = await recordedFaustVersion(outPath);
      if (!local) {
        console.warn(
          `[${moduleId}] skipping Faust drift check — \`faust\` is not on $PATH ` +
            `(committed artifact was built with ${recorded ?? "an unknown version"}).`
        );
        continue;
      }
      if (recorded && local !== recorded) {
        console.warn(
          `[${moduleId}] skipping Faust drift check — local Faust ${local} != ` +
            `${recorded} recorded in ${outPath}. Byte comparison across Faust ` +
            `versions is meaningless; install ${recorded} to check this module.`
        );
        continue;
      }
    } else if (!hasFaust()) {
      console.error(
        `[${moduleId}] ${dspPath} exists but \`faust\` is not on $PATH. ` +
          `Install Faust (e.g. \`brew install faust\`) and re-run \`mise run gen-faust\`.`
      );
      process.exit(1);
    }

    const cn = `${moduleId}_faust`;
    const tmpDir = await mkdtemp(join(tmpdir(), "moveforge-faust-"));
    const tmpOut = join(tmpDir, `${moduleId}_faust.c`);
    const result = spawnSync(
      "faust",
      ["-lang", "c", "-cn", cn, "-a", ARCH_FILE, dspPath, "-o", tmpOut],
      { encoding: "utf8" }
    );
    if (result.status !== 0) {
      console.error(`[${moduleId}] faust failed:\n${result.stderr}`);
      await rm(tmpDir, { recursive: true, force: true });
      process.exit(result.status ?? 1);
    }
    const body = await readFile(tmpOut, "utf8");
    await rm(tmpDir, { recursive: true, force: true });
    /* The Faust backend emits several functions with unused `dsp` /
     * `sample_rate` / `inputs` parameters. This file is #included into the
     * module's adapter, so it shares that translation unit and cannot take
     * per-file compiler flags — the suppression has to travel with the
     * generated artifact. Scoped with push/pop so the adapter's own code is
     * still checked. */
    const header =
      `/* GENERATED by scripts/gen-faust.ts from ${moduleId}.dsp via Faust */\n` +
      `/* Regenerate with: mise run gen-faust (or: pnpm run gen-faust) */\n\n` +
      `#pragma GCC diagnostic push\n` +
      `#pragma GCC diagnostic ignored "-Wunused-parameter"\n\n`;
    const footer = `\n#pragma GCC diagnostic pop\n`;
    const generated = header + body + footer;
    drift += await writeGeneratedFile({
      generated,
      mode,
      moduleId,
      outPath,
      staleMessage: "run `mise run gen-faust`",
      writeMessage: `wrote ${outPath}`
    });
  }

  if (any === 0) {
    console.log("No .dsp sources found — nothing to do.");
  }

  return drift;
}

async function exists(p: string): Promise<boolean> {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

function hasFaust(): boolean {
  return faustVersion() !== null;
}

/* e.g. "2.85.5" from `Faust Version 2.85.5`. */
function faustVersion(): string | null {
  const r = spawnSync("faust", ["--version"], { encoding: "utf8" });
  if (r.status !== 0 || !r.stdout) return null;
  const m = r.stdout.match(/Version\s+(\d+\.\d+\.\d+)/i);
  return m ? m[1] : null;
}

/* The version Faust stamped into an already-committed artifact. */
async function recordedFaustVersion(path: string): Promise<string | null> {
  try {
    const text = await readFile(path, "utf8");
    const m = text.match(/Code generated with Faust\s+(\d+\.\d+\.\d+)/);
    return m ? m[1] : null;
  } catch {
    return null;
  }
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2] === "--check" ? "check" : "write";
  const drift = await generate({ mode });
  if (mode === "check" && drift > 0) process.exit(1);
}
