/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of dustline_params.gen.inc so the param count and enum are
 * visible to dustline_core.h, which needs DUSTLINE_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking dustline_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef DUSTLINE_PARAMS_GEN_H
#define DUSTLINE_PARAMS_GEN_H

#define DUSTLINE_PARAM_COUNT 9

enum {
    DUSTLINE_PARAM_VOLUME = 0,
    DUSTLINE_PARAM_WAVE = 1,
    DUSTLINE_PARAM_NOISE = 2,
    DUSTLINE_PARAM_CUTOFF = 3,
    DUSTLINE_PARAM_RESONANCE = 4,
    DUSTLINE_PARAM_ATTACK = 5,
    DUSTLINE_PARAM_RELEASE = 6,
    DUSTLINE_PARAM_DRIVE = 7,
    DUSTLINE_PARAM_BEND_RANGE = 8
};

#endif
