/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of lobber_params.gen.inc so the param count and enum are
 * visible to lobber_core.h, which needs LOBBER_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking lobber_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef LOBBER_PARAMS_GEN_H
#define LOBBER_PARAMS_GEN_H

#define LOBBER_PARAM_COUNT 14

enum {
    LOBBER_PARAM_ACTIVE = 0,
    LOBBER_PARAM_OFFSET = 1,
    LOBBER_PARAM_DIVISION = 2,
    LOBBER_PARAM_MODE = 3,
    LOBBER_PARAM_LOOP = 4,
    LOBBER_PARAM_RATCHET = 5,
    LOBBER_PARAM_REVERSE = 6,
    LOBBER_PARAM_FREEZE = 7,
    LOBBER_PARAM_MUTE = 8,
    LOBBER_PARAM_CAPTURE = 9,
    LOBBER_PARAM_LOOP_BEATS = 10,
    LOBBER_PARAM_MIX = 11,
    LOBBER_PARAM_BPM = 12,
    LOBBER_PARAM_XFADE = 13
};

#endif
