/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of westfold_params.gen.inc so the param count and enum are
 * visible to westfold_core.h, which needs WESTFOLD_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking westfold_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef WESTFOLD_PARAMS_GEN_H
#define WESTFOLD_PARAMS_GEN_H

#define WESTFOLD_PARAM_COUNT 15

enum {
    WESTFOLD_PARAM_VOLUME = 0,
    WESTFOLD_PARAM_RATIO = 1,
    WESTFOLD_PARAM_SNAP = 2,
    WESTFOLD_PARAM_FM = 3,
    WESTFOLD_PARAM_FOLD = 4,
    WESTFOLD_PARAM_LPG = 5,
    WESTFOLD_PARAM_TONE = 6,
    WESTFOLD_PARAM_DRIVE = 7,
    WESTFOLD_PARAM_STRIKE = 8,
    WESTFOLD_PARAM_CHAOS = 9,
    WESTFOLD_PARAM_WIDTH = 10,
    WESTFOLD_PARAM_SUSTAIN = 11,
    WESTFOLD_PARAM_DECAY = 12,
    WESTFOLD_PARAM_RELEASE = 13,
    WESTFOLD_PARAM_BEND_RANGE = 14
};

#endif
