/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of faust_drive_params.gen.inc so the param count and enum are
 * visible to faust_drive_core.h, which needs FAUST_DRIVE_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking faust_drive_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef FAUST_DRIVE_PARAMS_GEN_H
#define FAUST_DRIVE_PARAMS_GEN_H

#define FAUST_DRIVE_PARAM_COUNT 4

enum {
    FAUST_DRIVE_PARAM_DRIVE = 0,
    FAUST_DRIVE_PARAM_TONE = 1,
    FAUST_DRIVE_PARAM_MIX = 2,
    FAUST_DRIVE_PARAM_LEVEL = 3
};

#endif
