#ifndef FAUST_DRIVE_CORE_H
#define FAUST_DRIVE_CORE_H

/* Public moveforge core API for the Faust-backed faust_drive module.
 *
 * The underlying DSP is generated by Faust from faust_drive.dsp into
 * faust_drive_faust.c. This header exposes a thin C adapter so the rest
 * of the moveforge pipeline (wrapper, host renderers, tests) treats the
 * module identically to a hand-written C module.
 */

typedef struct {
    float drive;
    float tone;
    float mix;
    float level;

    /* Opaque pointer to the Faust-generated DSP instance (faust_drive_faust*).
     * Allocated by faust_drive_init via newfaust_drive_faust(), freed by
     * faust_drive_destroy. */
    void *fdsp;

    /* Captured zone addresses (FAUSTFLOAT*) for each moveforge param id,
     * populated by buildUserInterface during init. Indexed by
     * FAUST_DRIVE_PARAM_* enum values. */
    void *zones[4];
} faust_drive_core_t;

void faust_drive_init(faust_drive_core_t *s);
void faust_drive_destroy(faust_drive_core_t *s);
void faust_drive_apply_defaults(faust_drive_core_t *s);
int faust_drive_param_id(const char *key);
void faust_drive_set_param(faust_drive_core_t *s, int param_id, float value);
float faust_drive_get_param(const faust_drive_core_t *s, int param_id);
void faust_drive_process_float(faust_drive_core_t *s,
                               const float *in_left, const float *in_right,
                               float *out_left, float *out_right,
                               int frames);

#endif
