/* GENERATED by scripts/gen-params.ts from module.json — do not edit. */
/* Regenerate with: mise run gen-params (or: pnpm run gen-params) */

/* Split out of arpy_params.gen.inc so the param count and enum are
 * visible to arpy_core.h, which needs ARPY_PARAM_COUNT to size
 * arrays that are indexed by param id. The .inc cannot serve that purpose: it
 * defines functions taking arpy_core_t*, so it has to be included *after* the
 * struct, which is too late. */

#ifndef ARPY_PARAMS_GEN_H
#define ARPY_PARAMS_GEN_H

#define ARPY_PARAM_COUNT 3

enum {
    ARPY_PARAM_PATTERN = 0,
    ARPY_PARAM_CHORD = 1,
    ARPY_PARAM_RATE = 2
};

#endif
